<?php

/**
 * Implements hook_menu().
 */
function vaxia_convert_menu() {
  $items['admin/settings/vaxia_convert'] = array(
    'title' => 'Vaxia Conversion',
    'access arguments' => array('access content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_vaxia_convert_admin_form'),
  );
  return $items;
}

function _vaxia_convert_admin_form() {
  $form['root_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to Old Vaxia'),
    '#description' => t('Path from server root, leave off ending slashes.'),
  );
  $form['step_one'] = array(
    '#type' => 'submit',
    '#value' => t('Import started do not start it again. If conversion failed, remove created files and retry.'),
    '#disabled' => TRUE,
    '#weight' => 1,
  );
  $form['step_two'] = array(
    '#type' => 'submit',
    '#value' => t('Not ready to import. Convert files first or check the server to make sure they converted.'),
    '#disabled' => TRUE,
    '#weight' => 2,
  );
  if (!file_exists('./vaxia_convert/users.xml')) {
    unset($form['step_one']['#disabled']);
    $form['#submit'] = array('_vaxia_convert_admin_form_submit_one');
    $form['step_one']['#value'] = t('Convert old Vaxia files. THIS WILL TAKE TIME. So give it minutes to complete.');
  }
  if (file_exists('./vaxia_convert/users.xml') && file_exists('./vaxia_convert/art.xml')
    && file_exists('./vaxia_convert/vaxia-rooms.xml') && file_exists('./vaxia_convert/sirian-rooms.xml')
    && file_exists('./vaxia_convert/characters.xml') && file_exists('./vaxia_convert/npcs.xml')
    && file_exists('./vaxia_convert/items.xml')) {
    unset($form['step_two']['#disabled']);
    $form['root_path']['#access'] = FALSE;
    $form['#submit'] = array('_vaxia_convert_admin_form_submit_two');
    $form['step_two']['#value'] = t('Import converted files into new Vaxia.');
  }
  return $form;
}

function _vaxia_convert_admin_form_submit_one($form, &$form_state) {
  module_load_include('inc', 'vaxia_convert', 'vaxia_conversion_script');
  drupal_set_message('Starting conversion.');
  $root_path = $form_state['values']['root_path'];
  vaxia_convert_main($root_path);
  drupal_set_message('Conversion completed.');
}

function _vaxia_convert_admin_form_submit_two($form, &$form_state) {
  module_load_include('inc', 'vaxia_convert', 'vaxia_import_script');
  drupal_set_message('Starting imports.');
  vaxia_import_main();
  drupal_set_message('Import completed.');
}
