<?php
/**
 * @file
 * Code for the Wiki features feature.
 */

include_once 'site_wiki.features.inc';

/**
 * Implements hook_permission().
 */
function site_wiki_permission() {
  return array(
    'edit locked site wiki'=> array(
      'title' => t('edit locked site wiki'),
      'description' => t('Edit a site wiki in a locked workflow state.'),
    ),
    'administer site wiki'=> array(
      'title' => t('administer site wiki'),
      'description' => t('Administer site wiki settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function site_wiki_menu() {
  $items['admin/config/system/site_wiki'] = array(
    'title' => 'Site wiki',
    'description' => 'Configure settings for the site wiki.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_site_wiki_admin_settings'),
    'access arguments' => array('administer site wiki'),
  );
  return $items;
}

/**
 * Implementation of admin settings form.
 */
function _site_wiki_admin_settings($form, &$form_state) {
  $form['site_wiki_templates'] = array(
    '#title' => t('Site wiki templates'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#tree' => TRUE,
  );
  // X templates, with Name and value.
  // And one blank set of fields to add more to it.
  $headers = array(
    t('Template name'),
    t('Template'),
  );
  $rows = array();
  $templates = variable_get('site_wiki_templates', array());
  foreach ($templates as $index => $template_data) {
    if (!empty($template_data['template_name'])) {
      $form['site_wiki_templates'][$index]['template_name'] = array(
        '#title' => t('Template_name'),
        '#type' => 'textfield',
        '#default_value' => $template_data['template_name'],
      );
      $form['site_wiki_templates'][$index]['template'] = array(
        '#title' => t('Template'),
        '#type' => 'textarea',
        '#default_value' => $template_data['template'],
      );
    }
  }
  $new_index = count($templates);
  $form['site_wiki_templates'][$new_index]['template_name'] = array(
    '#title' => t('Template name'),
    '#description' => t('The name the template will be listed under for the display.'),
    '#type' => 'textfield',
  );
  $form['site_wiki_templates'][$new_index]['template'] = array(
    '#title' => t('Template'),
    '#description' => t('The text of the template.'),
    '#type' => 'textarea',
  );
  return system_settings_form($form);
}

/**
 * Implements hook_menu_alter().
 */
function site_wiki_menu_alter($node, $op, $account) {
  if ($op == 'update' && $node->type == 'wiki_page' && _site_wiki_is_locked($node)) {
    return NODE_ACCESS_DENY;
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_node_presave().
 */
function site_wiki_node_presave($node) {
  // TMP removing this as a feature, pending correcting for double-nested links.
  return;
  // If node is a wiki page, add obvious links for cross linking..
  if ($node->type == 'wiki_page') {
    $body = $node->body[ $node->language ][0]['value'];
    // Get array of matches.
    $nodes = db_query('SELECT title, nid FROM {node} WHERE type = \'wiki_page\'');
    $replacements = array();
    foreach ($nodes as $values) {
      $replacements[' ' . $values->title . ' ' ] = ' [[' . $values->title . ']] ';
      $replacements[' ' . $values->title . '.' ] = ' [[' . $values->title . ']].';
      $replacements[' ' . $values->title . ',' ] = ' [[' . $values->title . ']],';
    }
    // Replace.
    $body = strtr($body, $replacements);
    // Put output back in.x
    $node->body[ $node->language ][0]['value'] = $body;
  }
  // And now proceed with the saving.
}

/**
 * Implements hook_block_info().
 */
function site_wiki_block_info() {
  $blocks = array();
  $blocks['site_wiki_templates'] = array(
    'info' => t('Site wiki templates'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['site_wiki_disamb'] = array(
    'info' => t('Site wiki disambiguation'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_freelinking_alter().
 */
function site_wiki_freelinking_alter(&$freelinking) {
  foreach ($freelinking as $plugin => $details) {
    // Only change for the nodetitle default freelink module.
    if ($plugin == 'nodetitle') {
      // Override the value for callback.
      $freelinking[$plugin]['callback'] = 'site_wiki_freelinking_nodetitle_callback';
    }
  }
}

/**
 * Implements hook_freelink_alter().
 */
function site_wiki_freelink_alter(&$link, $target, $plugin_name, $plugin) {
  // Trim title down to the last leaf for displaying the link.
  $title = $link[0];
  $title = explode('/', $title);
  if (is_array($title)) {
    $title = array_pop($title);
  }
  // And set it.
  $link[0] = $title;
}

/**
 * Implements hook_block_view().
 */
function site_wiki_block_view($delta = '') {
  $block = array();
  // Per delta, select an output.
  switch ($delta) {
    case 'site_wiki_templates':
      $templates = variable_get('site_wiki_templates', array());
      if (!empty($templates)) {
        $items = array();
        foreach ($templates as $index => $template_data) {
          if (!empty($template_data['template_name'])) {
            $items[] = '<span class="site_wiki_templates site_wiki_templates_' . $index . '">' .
              '<span class="site_wiki_template_name"><a href="#">' . check_plain($template_data['template_name']) . '</a></span>' .
              '<span class="site_wiki_template" style="display:none;">' . check_plain($template_data['template']) . '</span>' .
            '</span>';
          }
        }
        // Include the JS for this feature.
        drupal_add_js(drupal_get_path('module', 'site_wiki') . '/js/site_wiki.js');
        $block['subject'] = t('Wiki templates');
        $block['content'] = theme('item_list', array('items' => $items));
        $block['content'] .= '<div>' . t('These templates are provided to make it easier to quickly load a basic template for ' .
          'wiki articles. If you already have information in the page, or are not using a template feel free to ignore these links.') .
          '</div>';
      }
    break;
    case 'site_wiki_disamb':
      $block['subject'] = t('Wiki disambiguation');
      $block['content'] = '';
      // Find out if we have more than jsut this one node with the title.
      $path_root = arg(0);
      $nid = arg(1);
      if ($path_root == 'node' && is_numeric($nid)) {
        $node = node_load($nid);
        if ($node->type == 'wiki_page') {
          // Grab everything else with the same title and type.
          $others = db_query('SELECT nid FROM {node} WHERE type = \'wiki_page\' AND title = :title AND nid != :nid',
            array(':title' => $node->title, ':nid' => $node->nid));
          $found_others = array();
          foreach ($others as $other) {
            $other_node = node_load($other->nid);
            $sample = node_view($other_node,'teaser');
            $sample = substr(strip_tags($sample['body'][0]['#markup']),0,255);
            $found_others[] = t('Did you mean !link', array('!link' => l($other_node->title, 'node/' . $other_node->nid))) .
              ': <span class="wiki-disamb-sample" style="font-size:80%;">' . $sample . '</span>';
          }
          // Set up the links.
          if (!empty($found_others)) {
            $block['content'] = t('Other wiki articles share the same title...') . theme('item_list', array('items' => $found_others));
          }
        }
      }
    break;
    default:
      /// Do nothing.
    break;
  }
  // Include the css overall for addressing blocks as needed.
  drupal_add_css(drupal_get_path('module', 'site_wiki') . '/css/site_wiki.css');
  return $block;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function site_wiki_form_wiki_page_node_form_alter(&$form, &$form_state) {

  // Save the old title so if it changes, we can update other wiki articles w/title.
  $form['site_wiki_old_title'] = array(
    '#type' => 'hidden',
    '#value' => $form['#node']->title,
  );

  // Allow permissioned user to edit the wiki.
  if (user_access('edit locked site wiki')) {
    return;
  }
  // Else check for workflow state.
  if (!empty($form['#node']->type) && $form['#node']->type == 'wiki_page' && _site_wiki_is_locked($form['#node'])) {
    drupal_set_message(t('This wiki article is locked. You are not allowed to edit it.'));
    foreach (element_children($form) as $child) {
      unset($form[$child]);
    }
  }
}

/**
 * Replacement callback for nodetitle plugin
 */
function site_wiki_freelinking_nodetitle_callback($target, $plugin) {
  $this_node = node_load(arg(1));
  $this_nid = !empty($this_node->nid) ? $this_node->nid : 0;
  // WIKI FEARTURE: This is where the big change is. Call diff function.
  $node = site_wiki_freelinking_nodetitle_nid_from_title($target, $this_nid);
  // If no node was found, identify proceed with configured failover
  if (!$node) {
    return _freelinking_nodetitle_failure($target);
  }
  // Construct values for link.
  $title = $target['text'] ? $target['text'] : $node->title;
  if (!$target['tooltip']) {
    $target['tooltip'] = freelinking_internal_tooltip('node', $node->nid);
  }
  // Return link structure.
  return array($title, 'node/' . $node->nid, array(
      'attributes' => array('title' => $target['tooltip']),
      'language' => $node->language,
  ));
}

/**
 * Grab the nid associated with the title.
 * Attempt some degree of language sensibility
 */
function site_wiki_freelinking_nodetitle_nid_from_title(&$target, $this_nid) {
  $title = $target['dest'];
  // Get any content type restriction.
  if (isset($target['type'])) {
    $type = check_plain($target['type']);
  }
  else {
    $type = variable_get('freelinking_nodetitle_searchcontenttype', 'none');
  }
  $sql = 'SELECT n.title, n.nid, n.language FROM {node} n ' .
    'WHERE n.title = :title ' .
    'AND n.nid != :nid'; 
  $params = array(':title' => $title, ':nid' => $this_nid);
  if ($type != 'none') {
    $sql .= ' AND n.type = :type';
    $params[':type'] = $type;
  }
  $result = db_query($sql, $params);
  $set = array();
  foreach ($result as $record) {
    $set[] = $record;
  }
  // WIKI FEATURE: This is where the big change is.
  // Allow partial match on title IFF not found on full match.
  if (empty($set)) {
    $sql = 'SELECT n.title, n.nid, n.language FROM {node} n ' .
      'WHERE n.title LIKE :title ' .
      'AND n.nid != :nid'; 
    $params = array(':title' => '%/' . $title, ':nid' => $this_nid);
    if ($type != 'none') {
      $sql .= ' AND n.type = :type';
      $params[':type'] = $type;
    }
    $result = db_query($sql, $params);
    $set = array();
    foreach ($result as $record) {
      $set[] = $record;
    }
  }
  // Still nothing? Ok. One last try.
  if (empty($set)) {
    $title_end = explode('/', $title);
    $title_end = array_pop($title_end);
    $sql = 'SELECT n.title, n.nid, n.language FROM {node} n ' .
      'WHERE n.title LIKE :title ' .
      'AND n.nid != :nid'; 
    $params = array(':title' => '%' . $title_end, ':nid' => $this_nid);
    if ($type != 'none') {
      $sql .= ' AND n.type = :type';
      $params[':type'] = $type;
    }
    $result = db_query($sql, $params);
    $set = array();
    foreach ($result as $record) {
      $set[] = $record;
    }
  }
  // And if nothing was found even then - only then return NULL.
  if (empty($set)) {
    return NULL;
  }
  // Language restriction. Includes next-best-language logic.
  $language = array(language_default('language'), '');
  if (module_exists('locale')) {
    if (isset($target['language'])) {
      array_unshift($language, $target['language']);
    }
    foreach ($language as $priority) {
      foreach ($set as $node) {
        if ($priority == $node->language) {
          $retn = $node;
          break 2;
        }
      }
    }
  }
  else {
    $retn = $set[0];
  }
  return $retn;
}

/**
 * Helper function, determine if the wiki page is locked.
 */
function _site_wiki_is_locked($node) {
  if (isset($node->nid) && $state = workflow_get_workflow_node_by_nid($node->nid)) {
    $state = workflow_get_workflow_states_by_sid($state->sid);
    if ($state->state == 'locked') {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Helper function for views.
 */
function _site_wiki_limit_categories_by_nodecount($tid, $limit = 5) {
  $count = count( taxonomy_select_nodes($tid, FALSE) );
  if ($count < $limit) {
    return TRUE;
  }
  return FALSE;
}