<?php

/**
 * @file
 * Provide additional javascript to supplement the dice roller.
 */

/**
 * Implements hook_permission().
 */
function background_changer_permission() {
  return array(
    'use background changer' => array(
      'title' => t('Use the background changer javascript'),
      'description' => t('Use the background changer javascript.'),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function background_changer_node_view($node, $view_mode = 'full', $langcode) {
  if (_rpg_chat_is_enabled($node->type) && $view_mode == 'full' ) {
    if (user_access('use background changer')) {
      drupal_add_js(drupal_get_path('module', 'background_changer').'/js/background_changer.js');
    }
  }
}
