<?php

/**
 * @file
 * Provide additional javascript to supplement the dice roller.
 */

/**
 * Implements hook_permission().
 */
function background_changer_permission() {
  return array(
    'use background changer' => array(
      'title' => t('Use the background changer javascript'),
      'description' => t('Use the background changer javascript.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function background_changer_init() {
  if (user_access('use background changer')) {
    drupal_add_js(drupal_get_path('module', 'background_changer').'/js/background_changer.js');
  }
}
