<?php
/**
 * @file
 * Rules integration for filedepot.
 */
 
/**
 * Rules actions.
 */
function filedepot_rules_rules_action_info() {
  $actions = array(
    'filedepot_rules_actions_create_folder' => array(
      'label' => t('Create a new folder'),
      'group' => t('Filedepot'),
      'parameter' => array(
        'owner' => array(
          'type' => 'user',
          'label' => t('Folder owner'),
        ),
        'folder_name' => array(
          'type' => 'text',
          'label' => t('Folder name'),
          'sanitize' => TRUE,
          'translatable' => TRUE,
        ),
        'parent_folder' => array(
          'type' => 'list<integer>',
          'label' => t('Parent folder'),
          'options list' => 'filedepot_rules_parent_folder_options',
        ),
        'description' => array(
          'type' => 'text',
          'label' => t('Description'),
          'sanitize' => TRUE,
          'translatable' => TRUE,
        ),
        'inherit_permission' => array(
          'type' => 'boolean',
          'label' => t('Inherit parent permission'),
        ),
      ),
    ),
  );
  return $actions;
}

/**
 * Helper, generates the possible parent folders for selection on create / update.
 */
function filedepot_rules_parent_folder_options() {
  // Grab the right include file form filedepot.
  module_load_include('php', 'filedepot', 'lib-common');
  // Gather all of the available folders as if an admin.
  $parentFolders = array(0 => t('Top Level Folder'));
  $parentFolders += filedepot_recursiveAccessArray(array('admin'));
  return $parentFolders;
}

/**
 * The action function for filedepot_rules_actions_create_folder().
 */
function filedepot_rules_actions_create_folder($owner, $name, $parent, $description, $inherit_permission) {
  // Clean data.
  $name = check_plain($name);
  $description = check_plain($description);
  // Setup the node.
  $node = new stdClass();
  $node->type = 'filedepot_folder';
  node_object_prepare($node);
  $node->language = LANGUAGE_NONE;
  $node->uid = $owner->uid;
  $node->name = $owner->name;
  $node->title = check_plain($name);
  $node->description = check_plain($name);
  $node->filedepot_folder_desc[$node->language][0]['value'] = $description;
  $node->parentfolder = $parent;
  $node->inherit = $inherit_permission;
  // Save.
  node_save($node);
}