<?php
/**
 * @file
 * Code for Vaxia chatrooms.
 */

/**
 * Implements hook_permission().
 */
function vaxia_chatrooms_permission() {
  return array(
    'view vaxia ic chat' => array(
      'title' => t('View Vaxia IC chat'),
      'description' => t('View Vaxia IC chat conversations.'),
    ),
    'bypass vaxia ic chat' => array(
      'title' => t('Bypass Vaxia IC chat limits'),
      'description' => t('View Vaxia IC chat conversations even if not normally allowed.'),
    ),
  );
}

/*
 * Implements hook_node_view().
 */
function vaxia_chatrooms_node_view($node, $view_mode, $langcode) {

  if ($view_mode == 'full' && $node->type == 'rpg_chatroom') {

    // Check permissions.
    global $user;
    if (!user_access('bypass vaxia ic chat') && _vaxia_chatrooms_is_mature($node) && !_vaxia_chatrooms_is_user_mature($user)) {
      drupal_set_message('You are not allowed to view this room. You are underage.');
      watchdog('vaxia_room', 'Underage user forwarded to front page.');
      drupal_goto();
    }

    if (!user_access('bypass vaxia ic chat') && _vaxia_chatrooms_is_locked($node) && !_vaxia_chatrooms_is_on_lock_list($node, $user)) {
      drupal_set_message('You are not allowed to view this room. This room is locked.');
      watchdog('vaxia_room', 'Not on private list user forwarded to front page.');
      drupal_goto();
    }

    if (!user_access('bypass vaxia ic chat') && !_vaxia_chatrooms_is_ooc($node) && !user_access('view vaxia ic chat')) {
      drupal_set_message('You are not allowed to view this room. This room is locked to anonymous users.');
      drupal_goto();
    }

    if (!user_access('bypass vaxia ic chat') && function_exists('shadowban_is_banned_user') && shadowban_is_banned_user($user)) {
      if (_vaxia_chatrooms_is_mature($node) || _vaxia_chatrooms_is_locked($node)) {
        drupal_set_message('You are not allowed to view this room. This room is locked to other users.');
        drupal_goto();
      }
    }

    // If node is an RPG chatroom, add the js, css for additional behaviors for Vaxia specifically.
    drupal_add_js(drupal_get_path('module', 'vaxia_chatrooms') . '/js/vaxiaPullouts.js');
    drupal_add_css(drupal_get_path('module', 'vaxia_chatrooms') . '/css/vaxiaPullouts.css');
  }

}

/**
 * Implements process suggestion for node theme. This allows us to override parts of the node form.
 */
function vaxia_chatrooms_process_node(&$variables) {
  if (_rpg_chat_is_enabled($variables['node']->type)) {
    $rpg_class = 'ic-room';
    $limbo_room = variable_get('vaxia_limbo_room', array());
    // Set narrative checkbox access and no access in limbo rooms.
    if (!user_access('post in narrative format') || _vaxia_chatrooms_is_ooc($variables['node'])) {
      $rpg_class = 'ooc-room';
    }
    $variables['classes'] .= ' ' . $rpg_class;
  }
}

/**
 * Helper function determine if removed.
 */
function _vaxia_chatrooms_is_mature($node) {
  if (!isset($node->nid)) {
    return FALSE;
  }
  if (!isset($node->character_sheet_system) || !isset($node->workflow)) {
    $node = node_load($node->nid);
  }
  // Figure out the workflow for the node.
  $is_room_18 = isset($node->field_mature_posting['und'][0]['value']) ? $node->field_mature_posting['und'][0]['value'] : 0;
  if ($is_room_18) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper function determine if removed.
 */
function _vaxia_chatrooms_is_user_mature($user) {
  if (!isset($user->uid)) {
    global $user;
  }
  $this_user = user_load($user->uid);
  $is_user_18 = isset($this_user->field_mature['und'][0]['value']) ? $this_user->field_mature['und'][0]['value'] : 0;
  if (!$is_user_18) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Helper function determine if removed.
 */
function _vaxia_chatrooms_is_locked($node) {
  if (!isset($node->nid)) {
    return FALSE;
  }
  if (!isset($node->character_sheet_system) || !isset($node->workflow)) {
    $node = node_load($node->nid);
  }
  $is_locked = isset($node->field_locked_to_users['und'][0]['value']) ? $node->field_locked_to_users['und'][0]['value'] : 0;
  if ($is_locked) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper function determine if ooc.
 */
function _vaxia_chatrooms_is_on_lock_list($node, $user) {
  if (!isset($node->nid)) {
    return FALSE;
  }
  if (!isset($node->character_sheet_system) || !isset($node->workflow)) {
    $node = node_load($node->nid);
  }
  if (!isset($user->uid)) {
    global $user;
  }
  $this_user = user_load($user->uid);
  $room_users = isset($node->field_users['und']) ? $node->field_users['und'] : array();
  foreach ($room_users as $room_user) {
    if ($room_user['uid'] == $this_user->uid) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Helper function determine if ooc.
 */
function _vaxia_chatrooms_is_ooc($node) {
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  // Check the workflow.
  return _vaxia_is_ic_room($node);
}