<?php
/**
 * @file
 * Provide a search system into the old Vaxia archives.
 */

/**
 * Implements hook_permission().
 */
function vaxia_archives_permission() {
  return array(
    'search old archives'=> array(
      'title' => t('search old archives'),
      'description' => t('Search old archives.'),
    ),
    'administer old archives'=> array(
      'title' => t('administer old archives'),
      'description' => t('Administer old archives.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function vaxia_archives_menu() {
  $items['vaxia_archives'] = array(
    'title' => 'Archives',
    'description' => 'Old Vaxia archives',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('search old archives'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vaxia_archives_form'),
  );
  $items['admin/config/search/vaxia_archives'] = array(
    'title' => 'Vaxia archive configurations',
    'description' => 'Old Vaxia archive configurations',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer old archives'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vaxia_archives_admin_form'),
  );
  return $items;
}

/**
 * Menu callback for search page.
 */
function vaxia_archives_form($form, &$form_state) {
  $root = variable_get('vaxia_archives_flat_file_path', '');
  // Generate form.
  $form = array();
  $form['vaxia_archives_style'] = array(
    '#type' => 'item',
    '#markup' => '<style>' .
      '#vaxia-archives-form .form-type-textfield{float:left;margin-left:1em;height:40px;}' .
      '#vaxia-archives-form .form-type-select{float:left;margin-left:1em;height:40px;}' .
      '#vaxia-archives-form .form-type-select select{width:12em;}' .
      '#vaxia-archives-form .form-type-radios{float:left;margin-left:1em;height:40px;}' .
      '#vaxia-archives-form #edit-vaxia-archives-date{float:left;margin-left:1em;height:40px;}' .
      '#vaxia-archives-form #edit-vaxia-archives-date select{width:5em;}' .
      '#vaxia-archives-form #edit-vaxia-archives-date .form-type-select{float:left;margin-left:1em;}' .
      '#vaxia-archives-form #edit-vaxia-archives-submit{clear:left;}' .
      '</style>',
  );
  $form['search_fieldset'] = array(
    '#type' => 'fieldset',
  );
  $form['search_fieldset']['vaxia_archives_specifics'] = array(
    '#title' => t('Specifics'),
    '#type' => 'fieldset',
    //'#description' => t('Enter a date to limit results to that date.'),
  );
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_date'] = array(
    '#title' => t('Date'),
    '#type' => 'fieldset',
    //'#description' => t('Enter a date to limit results to that date.'),
  );
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_date']['vaxia_archives_date_month'] = array(
    '#type' => 'select',
    '#options' => array(
      'any' => '--',
      '01' => 'Jan',
      '02' => 'Feb',
      '03' => 'Mar',
      '04' => 'Apr',
      '05' => 'Map',
      '06' => 'Jun',
      '07' => 'Jul',
      '08' => 'Aug',
      '09' => 'Sep',
      '10' => 'Oct',
      '11' => 'Nov',
      '12' => 'Dec',
    ),
  );
  $day_ranges = range(1, 31);
  foreach ($day_ranges as $day_range) {
    if ($day_range < 10) {
      $day_range = '0' . $day_range;
    }
    $days[$day_range] = $day_range;
  }
  $days = array_combine($days, $days);
  $days = array('any' => '--') + $days;
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_date']['vaxia_archives_date_day'] = array(
    '#type' => 'select',
    '#options' => $days,
  );
  $years = array_combine(range(2004, date('Y')), range(2004, date('Y')));
  $years = array('any' => '--') + $years;
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_date']['vaxia_archives_date_year'] = array(
    '#type' => 'select',
    '#options' => $years,
  );
  $location = _vaxia_archives_read_data_file($root .'/d/location.data');
  asort($location);
  $location = array('any' => '--') + $location;
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_location'] = array(
    '#title' => t('Location'),
    '#type' => 'select',
    //'#description' => t('Enter a location to search for the location in the archive filename.'),
    '#options' => $location,
    '#default_value' => 'any',
  );
  $character = _vaxia_archives_read_data_file($root .'/d/character.data');
  asort($character);
  $character = array('any' => '--') + $character;
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_character'] = array(
    '#title' => t('Character'),
    '#type' => 'select',
    //'#description' => t('Enter a character to search for the location in the archive filename and text.'),
    '#options' => $character,
    '#default_value' => 'any',
  );
  $player = _vaxia_archives_read_data_file($root .'/d/player.data');
  asort($player);
  $player = array('any' => '--') + $player;
  $form['search_fieldset']['vaxia_archives_specifics']['vaxia_archives_player'] = array(
    '#title' => t('Player'),
    '#type' => 'select',
    //'#description' => t('Enter a character to search for the location in the archive filename and text.'),
    '#options' => $player,
    '#default_value' => 'any',
    '#suffix' => '<div style="clear:both;">&nbsp;</div>',
  );
  $form['search_fieldset']['vaxia_archives_contents'] = array(
    '#title' => t('Contents'),
    '#type' => 'fieldset',
    //'#description' => t('Enter a date to limit results to that date.'),
  );
  $form['search_fieldset']['vaxia_archives_contents']['vaxia_archives_text'] = array(
    '#title' => t('Text'),
    '#type' => 'textfield',
    //'#description' => t('Enter any string to search for the location in the archive text.'),
    '#size' => 15,
  );
  $form['search_fieldset']['vaxia_archives_contents']['vaxia_archives_type'] = array(
    '#title' => t('Type'),
    '#type' => 'radios',
    //'#description' => t('Enter any string to search for the location in the archive text.'),
    '#options' => array(
      'any' => t('Any Post'),
      'room' => t('Chat Room Post'),
      'forum' => t('Forum Post'),
    ),
    '#default_value' => 'any',
    '#suffix' => '<div style="clear:both;">&nbsp;</div>',
  );
  $form['vaxia_archives_submit'] = array(
    '#type' => 'button',
    '#value' => t('Search archives'),
    '#ajax' => array(
      'callback' => 'vaxia_archives_form_ajax',
      'wrapper' => 'vaxia_archives_results',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
  $search_results = t('No search performed.');
  if (!empty($form_state['values']['vaxia_archives_date_month']) ||
    !empty($form_state['values']['vaxia_archives_date_day']) ||
    !empty($form_state['values']['vaxia_archives_date_year']) ||
    !empty($form_state['values']['vaxia_archives_type']) ||
    !empty($form_state['values']['vaxia_archives_location']) ||
    !empty($form_state['values']['vaxia_archives_character']) ||
    !empty($form_state['values']['vaxia_archives_player']) ||
    !empty($form_state['values']['vaxia_archives_text'])) {
    $search_results = _vaxia_archives_search(
      $form_state['values']['vaxia_archives_date_month'],
      $form_state['values']['vaxia_archives_date_day'],
      $form_state['values']['vaxia_archives_date_year'],
      $form_state['values']['vaxia_archives_type'],
      $form_state['values']['vaxia_archives_location'],
      $form_state['values']['vaxia_archives_character'],
      $form_state['values']['vaxia_archives_player'],
      $form_state['values']['vaxia_archives_text']
    );
  }
  $form['vaxia_archives_results'] = array(
    '#title' => t('Seach results'),
    '#type' => 'item',
    '#markup' => $search_results,
    '#prefix' => '<div id="vaxia_archives_results">',
    '#suffix' => '</div>',
  );
  if (!empty($root)) {
    $form['vaxia_archives_raw'] = array(
      '#title' => t('Raw files'),
      '#type' => 'item',
      '#markup' => '<br/>' .
        '<b><i><a href="' . $root . '" target="_blank">Direct link to archives</a></i></b>' .
        '<br/><br/>' .
        '<iframe src="' . $root . '" width="100%" height="500px"></iframe>',
      '#prefix' => '<div id="vaxia_archives_raw">',
      '#suffix' => '</div>',
    );
  }
  // Generate display of general index - iframe.
  return $form;
}

/**
 * AJAX callback for search form.
 */
function vaxia_archives_form_ajax($form, $form_state) {
  return $form['vaxia_archives_results'];
}

/**
 * Menu callback for admin page.
 */
function vaxia_archives_admin_form() {
  $form = array();
  $form['vaxia_archives_flat_file_path'] = array(
    '#title' => t('Flat file archive location'),
    '#type' => 'textfield',
    '#default_value' => variable_get('vaxia_archives_flat_file_path', ''),
  );
  return system_settings_form($form);
}

/**
 * Helper function, read in a CSV .data file to get a list of returns.
 */
function _vaxia_archives_read_data_file($path) {
  $results = array();
  if (is_file($path) && ($file = fopen($path, 'r')) !== FALSE) {
    while (($row = fgetcsv($file, 1000, ",")) !== FALSE) {
      if (!empty($row[0])) {
        $results[$row[0]] = $row[0];
      }
    }
  }
  return $results;
}

/**
 * Helper function, make a list of searchable results.
 * THIS IS NOT A 'proper' SEARCH SYSTEM.
 */
function _vaxia_archives_search($month = 'any', $day = 'any', $year = 'any', $type = 'any', $location, $character, $player, $text) {
  // Is the date set? Check that set path instead of all.
  $root = variable_get('vaxia_archives_flat_file_path', '');

  // Set the path if thos values were selected.
  $path = $root;
  if (!empty($year) && $year != 'any') {
    $path = $root . '/' . $year; // Since only the archives are org by year.
  }
  if (!empty($year) && $year != 'any' && !empty($month) && $month != 'any') {
    $path = $path . '/' . $month ;
  }
  if (!empty($year) && $year != 'any' && !empty($month) && $month != 'any' && !empty($day) && $day != 'any') {
    $path = $path . '/' . $day ;
  }
  if (!empty($year) && $year != 'any' && !empty($month) && $month != 'any' && !empty($day) && $day != 'any' && !empty($type) && $type != 'any') {
    $path = $path . '/' . $type ;
  }

  // Scrub the other values.
  $location = trim($location);
  $character = trim($character);
  $player = trim($player);
  $text = trim(addslashes(strip_tags($text)));

  // Start from the root.
  $root = variable_get('vaxia_archives_flat_file_path', '');

  // Check location name in file and content
  $found = array();
  // If date was the only thing set, first get the contents of that folder
  if (!empty($year) && $year != 'any') {
    $this_found = array();
    $output = '';
    $command = 'find -L ' . DRUPAL_ROOT . '/' . $path;
    exec($command, $output);
    foreach ($output as $found_file) {
      $this_found[] = $found_file;
    }
    foreach ($this_found as $index => $found_path) {
      $length = drupal_strlen(DRUPAL_ROOT) + drupal_strlen($root) + 2;
      $this_found[$index] = drupal_substr($found_path, $length);
    }
    $found = empty($found) ? $this_found : array_intersect($found, $this_found);
  }

  // Check for location info.
  if (!empty($location) && $location != 'any') {
    $this_found = _vaxia_archives_read_data_file($root .'/d/location.' . str_replace(' ', '-', $location) . '.data');
    // Only use the results that show under both.
    if (empty($this_found)) {
      $found = array();
    }
    $found = empty($found) ? $this_found : array_intersect($found, $this_found);
  }

  // Check character name in content
  if (!empty($character) && $character != 'any') {
    $this_found = _vaxia_archives_read_data_file($root .'/d/character.' . str_replace(' ', '-', $character) . '.data');
    // Only use the results that show under both.
    if (empty($this_found)) {
      $found = array();
    }
    $found = empty($found) ? $this_found : array_intersect($found, $this_found);
  }

  // Check player name in content
  if (!empty($player) && $player != 'any') {
    $this_found = _vaxia_archives_read_data_file($root .'/d/player.' . str_replace(' ', '-', $player) . '.data');
    // Only use the results that show under both.
    if (empty($this_found)) {
      $found = array();
    }
    $found = empty($found) ? $this_found : array_intersect($found, $this_found);
  }

  // Check text in content
  if (!empty($text)) {
    $this_found = array();
    $output = '';
    $command = 'grep -R -i "' . $text . '" ' . DRUPAL_ROOT . '/' . $path;
    exec($command, $output);
    foreach ($output as $found_file) {
      $found_file_parts = explode(':', $found_file);
      $this_found[] = $found_file_parts[0];
    }
    foreach ($this_found as $index => $found_path) {
      $length = drupal_strlen(DRUPAL_ROOT) + drupal_strlen($root) + 2;
      $this_found[$index] = drupal_substr($found_path, $length);
    }
    // Only use the results that show under both.
    if (empty($this_found)) {
      $found = array();
    }
    $found = empty($found) ? $this_found : array_intersect($found, $this_found);
  }

  // Clean up the found paths for proper links through
  global $base_url;
  foreach ($found as $index => $found_path) {
    $found_path = $root . '/' . $found_path;
    $new_path = '<a href="' . $base_url . '/' . $found_path . '" target="_blank">' . $found_path . '</a>';
    $found[$index] = $new_path;
  }

  // Create results
  if (!empty($found)) {
    $results = '<ul><li>' . implode("</li>\n<li>", $found) . '</li></ul>';
  }
  else {
    $results = '<ul><li>' . t('No results found.') . '</li></ul>';
  }
  return $results;
}