<?php
/**
 * @file
 * Code for the Vaxia feature.
 */

include_once('vaxia.features.inc');

include_once('vaxia.dice.inc');

include_once('vaxia.character_sheet.inc');

include_once('vaxia.helper.inc');

/**
 * Implements hook_permission().
 */
function vaxia_permission() {
  return array(
    'post in narrative format' => array(
      'title' => t('post in narrative format'),
      'description' => t('Post in narrative format.'),
    ),
    'transfer rxp' => array(
      'title' => t('transfer rxp'),
      'description' => t('Transfer RXP of your own sheets.'),
    ),
    'use SH dice options' => array(
      'title' => t('use SH dice options'),
      'description' => t('Use SH dice options.'),
    ),
    'transfer others sheets' => array(
      'title' => t('transfer others sheets'),
      'description' => t('Transfer the XP of others sheets.'),
    ),
    'create SHs' => array(
      'title' => t('create SHs'),
      'description' => t('Create SHs for running games.'),
    ),
    'edit SH notes' => array(
      'title' => t('edit SH notes'),
      'description' => t('Edit SH notes.'),
    ),
    'edit private SH notes' => array(
      'title' => t('edit private SH notes'),
      'description' => t('Edit private SH notes.'),
    ),
    'admin vaxia settings' => array(
      'title' => t('admin vaxia settings'),
      'description' => t('Administrate Vaxia settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function vaxia_menu() {
  // Autocompletes.
  $items['vaxia/transfer_xp'] = array(
    'title' => 'Transfer XP autocomplete',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_vaxia_transfer_xp_autocomplete',
  );
  // Menu items that are basically just menu blocks.
  $items['admin/vaxia'] = array(
    'title' => 'Vaxia',
    'description' => 'Administer Vaxia settings',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('admin vaxia settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/vaxia/vaxia'] = array(
    'title' => 'Vaxia',
    'description' => 'Administer Vaxia settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_vaxia_admin_settings_form'),
    'access arguments' => array('admin vaxia settings'),
  );
  return $items;
}

/**
 * Menu callback.
 */
function _vaxia_admin_settings_form($form, &$form_state) {
  // Character sheet is already included.
  if (function_exists('_vaxia_admin_settings')) {
    $form = array_merge($form, _vaxia_admin_settings());
  }
  return system_settings_form($form);
}

/**
 * Implements hook_rules_event_info().
 */
function vaxia_rules_event_info() {
  $items = array(
    'vaxia_gain_kxp' => array(
      'label' => t('Vaxia gain kxp'),
      'group' => t('Vaxia'),
      'variables' => array(
        'user' => array(
            'type' => 'user',
            'label' => t('Player'),
        ),
        'character' => array(
            'type' => 'node',
            'label' => t('Character'),
        ),
        'location' => array(
            'type' => 'node',
            'label' => t('Location'),
        ),
        'xp_amount' => array(
            'type' => 'integer',
            'label' => t('XP Amount'),
         ),
      ),
    ),
    'vaxia_gain_xp' => array(
      'label' => t('Vaxia gain xp'),
      'group' => t('Vaxia'),
      'variables' => array(
        'user' => array(
            'type' => 'user',
            'label' => t('Player'),
        ),
        'character' => array(
            'type' => 'node',
            'label' => t('Character'),
        ),
        'xp_amount' => array(
            'type' => 'integer',
            'label' => t('XP Amount'),
         ),
        'xp_type' => array(
            'type' => 'text',
            'label' => t('XP type'),
         ),
      ),
    ),
  );
  return $items;
}

/**
 * Implements hook_entity_info_alter().
 */
function vaxia_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['artwork'] = array(
    'label' => t('Secondary'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_theme().
 *
 * Register themes used by this module.
 */
function vaxia_theme($existing, $type, $theme, $path) {
  return array(
    'vaxia_dice_roller' => array(
      'render element' => 'element',
      'function' => 'theme_vaxia_dice_roller',
    ),
  );
}

/**
 * Get messages for feedback.
 */
function _vaxia_check_minmax_flags($node) {
  $stat_max = variable_get('vaxia_pc_stat_spend_cap', 225);
  $max_max = variable_get('vaxia_pc_stat_high_cap', 4);
  $zero_max = variable_get('vaxia_pc_stat_zero_cap', 1);
  $high_skill = variable_get('vaxia_pc_skill_max', 40);
  $high_stat = variable_get('vaxia_pc_stat_max', 40);
  $stat_max_warn = variable_get('vaxia_pc_stat_spend_warn', 210);
  $min_warn = variable_get('vaxia_pc_skill_warn', 10);
  $max_max = variable_get('vaxia_pc_stat_high_warn', 3);    
  $min_max = variable_get('vaxia_pc_stat_min_warn', 2);
  $skill_ave_warn = variable_get('vaxia_pc_skill_ave_warn', 20);

  // Field info.
  $messages = array();
  $fields_info = _character_sheet_get_field_info($node);
  // Gather data on spending.
  $spent_xp = array(); // XP by type.
  $spent_on_stats = 0; // Amount spent on stats.
  $spent_on_skills = 0; // Amount spent on skills.
  $maxed_values = 0; // Number of maxed values.
  $zero_skills = 0; // Number of zeroth sklls.
  $low_stats = 0; // Number of low stats.
  $low_vals = 0; // Number of low anyting.
  $numb_skills = 0; // Number of skills.
  // Loop through field data.
  $node_data = (array) $node;
  foreach ($fields_info as $field_key => $field_info) {
    if (isset($field_info['costs']['xp_type'])) {
      // Calculate cost difference.
      $totals = _vaxia_get_field_value_flat($node, $field_key, $fields_info);
      $cost = $totals['total'];
      $xp_type = $field_info['costs']['xp_type'];
      // Track for stat spending.
      if ($field_key != 'field_skill_value') {
        $spent_on_stats += $cost;
        // Too high.
        if ($cost >= $high_stat) {
          $maxed_values++;
        }
        // Low stat.
        if ($cost < $min_warn) {
          $low_stats++;
        }
        // Low values.
        if ($cost <= $min_warn) {
          $low_vals++;
        }
      }
      else {
        $spent_on_skills += $cost;
        $numb_skills = $totals['number'];
        foreach(element_children($node_data) as $this_field) {
          if ($this_field == 'field_skill') {
            $lang = $node->language;
            $skill_data = $node->$this_field;
            foreach ($skill_data as $skills) {
              foreach ($skills as $delta => $skill_data) {
                $skill_info = field_collection_item_load($skill_data['value']);
                $skill_cost = $skill_info->field_skill_value['und'][0]['value'];
                // Max sills.
                if ($skill_cost >= $high_skill) {
                  $maxed_values++;
                }
                // Zero skills.
                if (is_array($skill_data) && $skill_cost == 0) {
                  $zero_skills++;
                }
                // Low skill.
                if ($skill_cost <= $min_warn) {
                  $low_vals++;
                }
              }
            }
          }
        }
      } // End skills.
      $spent_xp[$xp_type] = isset($spent_xp[$xp_type]) ? $spent_xp[$xp_type] + $cost : $cost;
      // Over spent XP.
    }
  } // End loop.
  // Any under value stat.
  if ($low_stats > 1) {
    $messages[] = t('You have %low_stats stat below %min_warn. We recommend having higher stats.',
        array('%low_stats' => $low_stats, '%min_warn' => $min_warn));    
  }
  // More than two low stats or skills.
  if ($low_vals > $min_max) {
    $messages[] = t('You have %low_vals values at %min_warn or below. We recommend no more than %min_max low values.',
        array('%low_vals' => ($low_vals), '%min_warn' => $min_warn, '%min_max' => $min_max));    
  }
  // Focused too much on stats.
  if ($spent_on_stats > $stat_max_warn) {
    $messages[] = t('You have spent %spent_on_stats points on stats. We recommend no more than %stat_max on stats.',
        array('%spent_on_stats' => $spent_on_stats, '%stat_max' => $stat_max_warn));    
  }
  // Too many maxes.
  if ($maxed_values > $max_max) {
    $messages[] = t('You have %maxed_values maximized values.  We recommend no more than %max_max maxed values.',
        array('%maxed_values' => $maxed_values, '%max_max' => $max_max));
  }
  // Existing warning on averages.
  $skill_average = ($numb_skills > 0) ? $spent_on_skills / $numb_skills : 0;
  if ($skill_average < $skill_ave_warn) {
    $messages[] = t('You have an average of %skill_average on skills. We recommend having higher skills on average.',
      array('%spent_on_stats' => $spent_on_stats, '%skill_average' => number_format($skill_ave_warn, 2)));
  }
  // Return the messages.
  return $messages;
}

/**
 * Implements hook_node_update().
 */
function vaxia_node_update($node) {
  if (_character_sheet_is_enabled($node)) {
    // Flush Entity Cache record.
    if (module_exists('entitycache')) {
      cache_clear_all('*', 'cache_entity_node', TRUE);
    }
  }
}

/**
 * Implements hook_comment_insert().
 */
function vaxia_comment_presave($comment) {
  $node = node_load($comment->nid);
  $lang = $comment->language;
  if (_rpg_chat_is_enabled($node->type) && isset($comment->field_comment_character[$lang][0]['nid'])) {
    $character = node_load($comment->field_comment_character[$lang][0]['nid']);
    if (isset($character->nid)) {
      // If we have a character, save the character's info to the comment info.
      $comment->field_description[$lang][0] = isset($character->field_description[$lang][0]) ? $character->field_description[$lang][0] : '';
      $comment->field_comment_presence[$lang][0] = isset($character->field_presence[$lang][0]) ? $character->field_presence[$lang][0] : '';
      $comment->field_charisma[$lang][0] = isset($character->field_charisma[$lang][0]) ? $character->field_charisma[$lang][0] : '';
      $comment->field_comment_appearance[$lang][0] = isset($character->field_appearance[$lang][0]) ? $character->field_appearance[$lang][0] : '';
    }
  }
}

/**
 * Implements hook_workflow().
 */
function vaxia_workflow($op, $old_state, $new_state, $node, $force = FALSE) {
  switch ($op) {
    case 'transition post';
      // Flush Entity Cache record.
      if (module_exists('entitycache')) {
        cache_clear_all('*', 'cache_entity_node', TRUE);
      }
    break;
  }
}

/**
 * Implements process suggestion for comment theme. This allows us to override parts of the comment form.
 * This code is executed on display of the comment.
 */
function vaxia_process_comment(&$variables) {
  // Set the defaults
  $comment = $variables['comment'];
  $lang = $comment->language;
  $color_codes = array('aqua', 'black', 'blue', 'fuchsia', 'gray', 'green', 'lime', 'maroon',
    'navy', 'olive', 'purple', 'red', 'silver', 'teal', 'white', 'yellow');

  // Update the user image for submission to no image.
  // Check for user profile settings.
  // Apply picture rules to All node types.
  $this_user = user_load($comment->uid);
  $variables['picture'] = _vaxia_create_avatar_image_link(-1, $this_user->name);
  if (isset($this_user->field_artwork_image[$lang][0]['fid'])) {
    $variables['picture'] = _vaxia_create_avatar_image_link(
      $this_user->field_artwork_image[$lang][0]['fid'], $this_user->name);
  }
  // If not, fall back to the commment itself.
  if (isset($comment->field_artwork[$lang][0]['nid'])) {
    $artwork = node_load($comment->field_artwork[$lang][0]['nid']);
    if (isset($artwork->field_artwork_image[$lang][0]['fid'])) {
      $variables['picture'] = _vaxia_create_avatar_image_link(
        $artwork->field_artwork_image[$lang][0]['fid'], $this_user->name);
    }
  }

  // Check for character type only on RPG type nodes. (and do some other work as well on RPG chat nodes)
  if (!empty($variables['node']) && !empty($variables['node']->type) && _rpg_chat_is_enabled($variables['node']->type)) {
    // Redo the submitted field for RPG chatrooms only.
    $variables['submitted'] = t('!username </br> !datetime',
      array('!username' => $variables['author'], '!datetime' => $variables['created']));
    // Add the variables for our narrative and colors.
    if(isset($comment->field_comment_narrative[$lang][0]['value'])
      && ($comment->field_comment_narrative[$lang][0]['value'] == 1) ) {
      $variables['classes'] .= ' rpg-chat-narrative';
    }
    // Add the style for the content background. Default from user.
    $bkcolor = !empty($this_user->field_background_color[$lang][0]['value']) 
      ? $this_user->field_background_color[$lang][0]['value'] : '555555';
    // Unless the comment has it's own set.
    $bkcolor = !empty($comment->field_background_color[$lang][0]['value']) 
      ? $comment->field_background_color[$lang][0]['value'] : $bkcolor;
    // Set the value.
    $bkcolor = strtolower(trim($bkcolor));
    $bkcolor = preg_replace("/[^0-9a-z]/i", '', $bkcolor); // Filter non-alphanumeric out.
    if (!in_array($bkcolor, $color_codes)) {
      $bkcolor = '#'. $bkcolor;
    }
    $variables['comment_background_color'] = $bkcolor;
    // Add the style attribute for our content color. Default from user.
    $color = !empty($this_user->field_comment_color[$lang][0]['value']) 
      ? $this_user->field_comment_color[$lang][0]['value'] : '111111';
    // Unless the comment has it's own set.
    $color = !empty($comment->field_comment_color[$lang][0]['value']) 
      ? $comment->field_comment_color[$lang][0]['value'] : $color;
    // Set the value.
    $color = strtolower(trim($color));
    $color = preg_replace("/[^0-9a-z]/i", '', $color); // Filter non-alphanumeric out.
    if (!in_array($color, $color_codes)) {
      $color = '#'. $color;
    }
    $variables['content']['comment_body']['#prefix'] = '<span style="color:' . $color . '">';
    $variables['content']['comment_body']['#suffix'] = '</span>';
  }

  // Now check for specific character values. Art, post color, etc.
  // This is also on any node type that has characters - so chatrooms for now only.
  // Good thing node_load caches else calling this for Every Comment would get really ugly.
  if (!empty($variables['node']) && !empty($variables['node']->type)
    && _rpg_chat_is_enabled($variables['node']->type) && isset($comment->field_comment_character[$lang][0]['nid'])) {
    $character = node_load($comment->field_comment_character[$lang][0]['nid']);
    if (isset($character->nid)) {
      // Set character comment color if the comment was not set.
      if (empty($comment->field_background_color[$lang][0]['value']) && isset($character->field_background_color[$lang][0]['value'])) {
        $bkcolor = strtolower(trim($character->field_background_color[$lang][0]['value']));
        $bkcolor = preg_replace("/[^0-9a-z]/i", '', $bkcolor); // Filter non-alphanumeric out.
        if (!in_array($bkcolor, $color_codes)) {
          $bkcolor = '#'. $bkcolor;
        }
        $variables['comment_background_color'] = $bkcolor;
      }
      // Set background comment color if the comment was not set.
      if (empty($comment->field_comment_color[$lang][0]['value']) && isset($character->field_post_color[$lang][0]['value'])) {
        $color = strtolower(trim($character->field_post_color[$lang][0]['value']));
        $color = preg_replace("/[^0-9a-z]/i", '', $color); // Filter non-alphanumeric out.
        if (!in_array($color, $color_codes)) {
          $color = '#'. $color;
        }
        $variables['content']['comment_body']['#prefix'] = '<span style="color:' . $color . '">';
        $variables['content']['comment_body']['#suffix'] = '</span>';
      }
      // Set character name, titles.
      $character_name = $character->title;
      if (isset($character->field_titles[$lang][0]['value'])) {
        $character_name = $character->field_titles[$lang][0]['value'] .' ' . $character_name;
      } 
      if (isset($character->field_last_name[$lang][0]['value'])) {
        $character_name .= ' ' . $character->field_last_name[$lang][0]['value'];
      }
      // Set character description.
      $char_desc = isset($comment->field_description[$lang][0]['value']) ? $comment->field_description[$lang][0]['value'] : '';
      $char_desc = check_plain($char_desc);
      if (strlen($char_desc) > 595) {
        $char_desc = drupal_substr($char_desc, 0, 600) . '...';
      }
      $options = array('attributes' => array('title' => $char_desc));
      $character_name = '<span class="rpgchat-character-name">' . l($character_name, 'node/' . $character->nid, $options) . '</span>' .
            '<span class="rpgchat-user-name">(' . l($this_user->name, 'user/' . $this_user->uid) . ')</span>';
      // Update the submission variables with name, description information.
      $variables['submitted'] = t('!username !datetime',
        array(
          '!username' => $character_name,
          '!datetime' => $variables['created'])
        );
      // Now work on the character art display. Setup the link options for the character pic.
      // Use the comment if available.
      $field_presence = isset($comment->field_comment_presence[$lang][0]['value']) ? $comment->field_comment_presence[$lang][0]['value'] : '';
      $field_charisma = isset($comment->field_charisma[$lang][0]['value']) ? $comment->field_charisma[$lang][0]['value'] : '';
      $field_appearance = isset($comment->field_comment_appearance[$lang][0]['value']) ? $comment->field_comment_appearance[$lang][0]['value'] : '';
      $alt = t('Presence: @pre, Charisma: @char, Appearance: @app',
        array('@pre' => $field_presence, '@char' => $field_charisma,'@app' => $field_appearance));
      $link_options = array('html' => TRUE, 'attributes' => array('target' => '_blank'));    
      // Set picture to the default value (vaxia logo) as the fallback if no other resource found.
      $variables['picture'] = l( _vaxia_create_avatar_image_link(-1, $character_name, $alt),
        'node/' . $character->nid, $link_options);
      // Check first against the selected comment for an artwork node.
      if (!empty($comment->field_artwork[$lang][0]['nid'])) {
        // Set picture to the attached art node for the comment.
        $artwork = node_load($comment->field_artwork[$lang][0]['nid']);
        if (!empty($artwork->field_artwork_image[$lang][0]['fid'])) {
          $variables['picture'] = l( _vaxia_create_avatar_image_link(
            $artwork->field_artwork_image[$lang][0]['fid'], $character->title, $alt),
              'node/' . $character->nid, $link_options);
        }
      }
      // Else, if the character has it's own artwork file, use that.
      elseif (!empty($character->field_artwork_image[$lang][0]['fid'])) {
        // Set picture to the attached file for the character node.
        $variables['picture'] = l( _vaxia_create_avatar_image_link(
          $character->field_artwork_image[$lang][0]['fid'], $character->title, $alt),
            'node/' . $character->nid, $link_options);
      }
      // And done, the comment is set for the character.
    } // End character exists.
  } // End character on comment.
}

/**
 * Helper function, given a fid return the image link.
 */
function _vaxia_create_avatar_image_link($fid, $name, $alt = '') {
  $artwork_image = file_load($fid);
  $default_filepath = drupal_get_path('module', 'vaxia') . '/images/vaxialogo.gif';
  $filepath = isset($artwork_image->uri) ? $artwork_image->uri : $default_filepath;
  if (isset($filepath)) {
    if (empty($alt)) {
      $alt = t("@user's picture.", array('@user' => $name));
    }
    // If the image does not have a valid Drupal scheme (for eg. HTTP) don't load image styles.
    if (module_exists('image') && file_valid_uri($filepath) 
      && $style = variable_get('user_picture_style', '')) {
      $picture = theme('image_style',
        array('style_name' => $style, 'path' => $filepath, 'alt' => $alt, 'title' => $alt));
    }
    else {
      $picture = theme('image', array('path' => $filepath, 'alt' => $alt, 'title' => $alt));
    }
    $attributes = array(
      'attributes' => array('title' => t('View profile.')),
      'html' => TRUE,
    );
    return $picture;
  }
}

/**
 * Theme the dice roller.
 */
function theme_vaxia_dice_roller($element) {
  $element = $element['element'];
  // Process the array.
  $rendered = array();
  foreach (element_children($element) as $child) {
    if ($child == 'dice' && is_array($element[$child])) {
      // Theme the dice.
      $header = array( t('#'), t('d'), t('stat'), t('skill'));
      $rows = array();
      $i = 0;
      foreach (element_children($element['dice']) as $dice) {
        $number = drupal_render($element['dice'][$i]['number']);
        $size = drupal_render($element['dice'][$i]['size']);
        $stat = drupal_render($element['dice'][$i]['stat']);
        $skill = drupal_render($element['dice'][$i]['skill']);
        $rows[] = array($number, $size, $stat, $skill);
        $i++;
      }
      if (!empty($rows)) {
        $rendered[] = theme('table', array('header' => $header, 'rows' => $rows));
      }
    }
    else {
      // Theme everything else the dice.
      $rendered[] = drupal_render($element[$child]);
    }
  }
  return implode($rendered);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vaxia_form_workflow_tab_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  $node = isset($form['node']['#value']) ? $form['node']['#value'] : '';
  $controlled_types =_vaxia_helper_controlled_types();
  if (!empty($node) && $user->uid == $node->uid) {
    if (in_array($node->type, $controlled_types)) {
      $workflow_name = $form['#wf']->name;
      $options = $form['workflow'][$workflow_name]['#options'];
      $index = array_search('approved', $options);
      if ($index !== FALSE && $index != $node->workflow) {
        drupal_set_message(t('You own this node, you cannot set it to approved. Currently: ' . $node->workflow_state_name));
        unset($options[$index]);
        $form['workflow'][$workflow_name]['#options'] = $options;
        $form['workflow'][$workflow_name]['#default_value'] = $node->workflow;
      }
    }
  }
}

/**
 * Helper function, mark controlled types.
 */
function _vaxia_helper_controlled_types() {
  return array('character_sheet', 'items');
}

/**
 * Implements hook_form_alter().
 */
function vaxia_form_alter(&$form, &$form_state, $form_id) {

  // If we're viewing a comment form, allow for user profile to set RPG chat additional fields.
  if (substr($form_id, 0, 7) == 'comment' && isset($form['#node'])) {
    // Eject if this is not a chat room type.
    $type = $form['#node']->type;
    if (!_rpg_chat_is_enabled($type)) {
      return;
    }
    // Set character controls.
    global $user;
    $character = node_load(variable_get('vaxia_last_character_' . $user->uid, -1));
    if (isset($character->title)) {
      $lang = $character->language;
      $form['field_comment_character'][$lang]['#default_value'][0] = $character->nid;
      if (isset($character->field_artwork[$lang][0]['nid'])) {
        $form['field_artwork'][$lang]['#default_value'][0] = $character->field_artwork[$lang][0]['nid'];
      }
      $kxp = _character_sheet_get_xp($character->nid, 'kxp');
      $xp = _character_sheet_get_xp($character->nid, 'xp');
      $spent_xp = _character_sheet_get_xp($character->nid, 'spent_xp');       
      $form['field_comment_character'][$lang]['#description'] = $kxp . ' / 70 KXP, ' . ($xp - $spent_xp) . ' XP';
    }
    // Set limits in limbo rooms.
    $lang = isset($form_state['values']['language']) ? $form_state['values']['language'] : 'und';
    $limbo_room = variable_get('vaxia_limbo_room', array());
    // Set the access for descriptive elements.
    $hidden_desc_fields = array('field_description', 'field_comment_presence', 'field_charisma', 'field_comment_appearance');
    foreach ($hidden_desc_fields as $hidden_desc_field) {
      $form[$hidden_desc_field][$lang]['#value'] = '';
      $form[$hidden_desc_field][$lang]['#access'] = FALSE;
      $form[$hidden_desc_field][$lang]['#type'] = 'hidden';
    }
    // Set narrative checkbox access and no access in limbo rooms.
    if (!user_access('post in narrative format') || in_array($form['#node']->nid, $limbo_room)) {
      $form['field_comment_narrative'][$lang]['#value'] = 0;
      $form['field_comment_narrative'][$lang]['#access'] = FALSE;
      $form['field_comment_narrative'][$lang]['#type'] = 'hidden';
    }
    // Remove the no character setting for non-Limbo rooms.
    if (!in_array($form['#node']->nid, $limbo_room)) {
      $options = $form['field_comment_character'][$lang]['#options'];
      if (is_array($options)) {
        $options = array_diff_key($options, array('_none' => '- None -'));
      }
      else {
        $options = array('_none' => '- None -');
      }
      $form['field_comment_character'][$lang]['#options'] = $options;
    }
    // Set up diceroller callbacks on character selection.
    $form['field_comment_character'][$lang]['#ajax'] = array(
      'callback' => '_vaxia_character_pick',
      'wrapper' => 'vaxia-dice-character',
      'method' => 'replace',
      'effect' => 'fade',
    );
    // Set player uid for pickup.
    $form['uid'] = array(
      '#type' => 'hidden',
      '#value' => $user->uid,
    );
    // Set submissions.
    $form['actions']['submit']['#value'] = t('Post');
    $form['#submit'][] = '_vaxia_comment_add_kxp_submit';
    $form['#submit'][] = '_vaxia_comment_redirect_submit';
    // Move things around to duplicate submit buttons.
    $new_post = $form['actions']['submit'];
    $new_post['#weight'] = -10;
    array_unshift($form, $new_post);
    $new_refresh = $form['actions']['refresh_chat'];
    $new_refresh['#weight'] = -11;
    array_unshift($form, $new_refresh);
  } // End alter for comment forms.

  return $form;
}

/**
 * Ajax callback for character selection.
 */
function _vaxia_character_pick($form, $form_state) {
  return isset($form['vaxia_rolls']) ? $form['vaxia_rolls'] : array();
}

/** 
 * Additional submit handler to add kxp for commenting as a character, not narrative.
 */
function _vaxia_comment_add_kxp_submit($form, $form_state) {
  // Set the last posted character or none as needed.
  global $user;
  $lang = $form_state['values']['language'];
  variable_set('vaxia_last_character_' . $user->uid, $form_state['values']['field_comment_character'][$lang][0]['nid']);
  // Ignore kxp for limbo rooms.
  $limbo_room = variable_get('vaxia_limbo_room', array());
  if (in_array($form['#node']->nid, $limbo_room)) {
    return;
  }
  // Otherwise, figure out how much kxp we're giving.
  // If posted as a character and not as narrative.
  if (!empty($form_state['values']['field_comment_character'][$lang][0]['nid']) ) {
    if (!empty($form['cid']['#value'])) {
      drupal_set_message('Editing an existing comment - no kxp will be awarded.');
      return;
    }
    // The character gains XP per wordcount.
    if (!empty($form_state['values']['comment_body'][$lang][0]['value'])) {
      $kxp = _vaxia_figure_kxp($form_state['values']['comment_body'][$lang][0]['value']);
      $character = node_load($form_state['values']['field_comment_character'][$lang][0]['nid']);
      // Posting with an NPC? Mark the XP to the SH character.
      if ($character->field_is_npc[$character->language][0]['value'] == 1) {
        global $user;
        $sh_character = _vaxia_get_SH_characters($user->uid);
        if (!empty($sh_character)) {
          $character = $sh_character;
        }
      }
      // Mark the XP.
      if ($character->type == 'character_sheet') {
        _vaxia_add_xp($character->nid, $kxp, 'kxp');
        if (function_exists('rules_invoke_event')) {
          $player = user_load($character->uid);
          $location = $form['#node'];
          rules_invoke_event('vaxia_gain_xp', $player, $character, $location, $kxp, 'kxp');
        }
      }
    }  
  }
}

/** 
 * Helper function, calculate kxp to give based on text.
 */
function _vaxia_figure_kxp($text) {
  $wordcount = strlen($text);
  if (is_numeric($wordcount)) {
    $kxp = (81.6) * ( exp( (0.00008) * ($wordcount)) - 1 );
    $kxp = substr($kxp, 0, 4);
    $max_kxp = variable_get('vaxia_max_kxp_post', 10);
    return $kxp <= $max_kxp ? $kxp : $max_kxp;
  }
  return 0;
}

/**
 * Redirection submit handler to clip the anchor.
 * This avoids wierd scroll down issues in the display.
 */
function _vaxia_comment_redirect_submit($form, &$form_state) {
  $form_state['redirect'] = 'node/' . $form_state['values']['nid'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vaxia_form_comment_form_alter(array &$form, array &$form_state) {
  // Disable the extra box on comment forms.
  $form['author']['subscriptions_notify']['#access'] = FALSE;
  // If comment revisions is included prevent users stealth-edits.
  if (module_exists('comment_revisions')) {
    if (!empty($form['revision_information']['revision'])) {
      $form['revision_information']['revision']['#access'] = FALSE;
      $form['revision_information']['revision']['#default_value'] = TRUE;
      $form['revision_information']['revision']['#value'] = TRUE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vaxia_form_character_sheet_node_form_alter(&$form, &$form_state, $form_id) {
  $node = isset($form['#node']) ? $form['#node'] : '';
  if (_character_sheet_is_enabled($node) && _character_sheet_is_playable($node)) {
    $user_sh = _vaxia_get_SH_characters($node->uid);
    global $user;
    $realm = _vaxia_get_realm($node);
    $form['#attributes']['class'][] = 'vaxia-realm-' . $realm;
    if ($node->uid == $user->uid) {
      $form['#attributes']['class'][] = 'vaxia-owner';
    }
    else {
      $form['#attributes']['class'][] = 'vaxia-not-owner';
    }
    // Edit the storyhost character specifically.
    if (!empty($node) && !empty($user) && !empty($user_sh) && $node->uid == $user->uid && $node->nid == $user_sh->nid) {
      $allowed_edit = array('field_personality', 'field_description', 'field_post_color',
        'field_sh_notes', 'field_sh_private_notes', 'field_player_notes', 'field_artwork_image');
      foreach (element_children($form) as $child) {
        if ((strpos($child, 'field_') === 0) && !in_array($child, $allowed_edit)) {
          $form[$child]['#disabled'] = TRUE;
          $form[$child]['#value'] = $form[$child]['#default_value'];
        }
        if ($child == 'title') {
          $form[$child]['#disabled'] = TRUE;
          $form[$child]['#value'] = $form[$child]['#default_value'];
        }
      }
      drupal_set_message('You are attempting to edit your Storyhost character sheet. ' .
        'Storyhosts are not playable characters, so your options are limited for this sheet.');
    }
  }
}


/**
 * Helper function, retrieve SH information from player.
 */
function _vaxia_get_SH_characters($uid) {
  static $SH_characters;
  if (!empty($SH_characters[$uid])) {
    return $SH_characters[$uid];
  }
  // Not in the cache? Look it up from the user.
  $user = user_load($uid);
  if (!empty($user->field_storyhost_character[$user->language][0]['value'])) {
    $SH_characters[$uid] = node_load( $user->field_storyhost_character[$user->language][0]['value'] );
    return $SH_characters[$uid];
  }
  // Not on the user either? Check nodes - and worse comes to worse, add it to the user.
  if (empty($user->field_storyhost_character[$user->language][0]['value'])) {
    $nodes = node_load_multiple(array(), array('type' => 'character_sheet', 'uid' => $uid));
    foreach ($nodes as $nid => $node) {
      if (isset($node->field_is_storyteller[$node->language][0]['value']) &&
        $node->field_is_storyteller[$node->language][0]['value'] == 1) {
        $SH_characters[$uid] = $node;
      }
    }
    // Save this value so we don't have to dig this deep again.
    $user->field_storyhost_character[$user->language][0]['value'] = $SH_characters[$uid];
    user_save($user);
    return $SH_characters[$uid];
  }
  // Still nothing? Ok - maybe there's actually nothing there. Set and return;
  $SH_characters[$uid] = array();
  return $SH_characters[$uid];
}

/**
 * Views helper function.
 */
function _vaxia_get_character_ref_types($nid) {
  global $user;
  $node = node_load($nid);
  $lang = $node->language;
  // Get values.
  $field_is_npc = isset($node->field_is_npc[$lang][0]['value']) ?
    $node->field_is_npc[$lang][0]['value'] : 0;
  $field_is_generic_npc = isset($node->field_is_generic_npc[$lang][0]['value']) ?
    $node->field_is_generic_npc[$lang][0]['value'] : 0;
  // Look for Generic NPCs.
  if ($field_is_npc == 1 && $field_is_generic_npc == 1) {
    return 'Generic NPCs';
  }
  // Look for any NPCs.
  if ($field_is_npc == 1) {
    return 'NPCs';
  }
  // Default is a Character.
  return 'Characters';
}

/**
 * Rules helper function.
 */
function _vaxia_filter_characters_by_room($nid) {
  $node = node_load(arg(1));
  $sh_tid = 1004;
  if (!empty($node) && !empty($node->field_tag_realm[$node->language][0]['tid']) && ($node->field_tag_realm[$node->language][0]['tid'] != $sh_tid)) {
    return $node->field_tag_realm[$node->language][0]['tid'] . '+' . $sh_tid;
  }
  return 'all';
}

/**
 * Helper function get the realm from the node.
 */
function _vaxia_get_realm($node, $field = 'field_tag_realm') {
  $realm = 'storyhost';
  if (!empty($node->{$field}[$node->language][0]['tid'])) {
    $realm_term = taxonomy_term_load($node->{$field}[$node->language][0]['tid']);
    $realm = !empty($realm_term->name) ? strtolower($realm_term->name) : $realm;
  }
  return $realm;
}