<?php
/**
 * @file
 * Add companion and drone item handling to the dice roller.
 */

/**
 * Implements hook_vaxia_dice_form_alter().
 */
function item_companions_vaxia_dice_form_alter(&$form, $form_state, $form_id) {
  // Get characters.
  $character = _vaxia_dice_roller_get_selected_character($form, $form_state);
  // If we have a character, figure out the rest of the display for it.
  if ($character && $character != '_none' ) {
    $character = node_load($character);
    // Only add a form if the character really exists.
    if (isset($character->title) && ($character->type == 'character_sheet')) {
      // Display the items under the stat and skill row.
      $companions = _item_companions_get_companions($character);
      if (!empty($companions)) {
        // Filter companions out of the item list.
        $companion_options = array('_none' => t('- None -'));
        foreach ($form['vaxia_rolls']['items']['#options'] as $nid => $item) {
          if (in_array($nid, array_keys($companions))) {
            unset($form['vaxia_rolls']['items']['#options'][$nid]);
            if (!empty($companions[$nid]->title)) {
              $companion_options[$nid] = $companions[$nid]->title;
            }
          }
        }
        // Add option for selecting the character.
        $form['vaxia_rolls']['as_companion'] = array(
          '#title' => t('Using companion'),
          '#type' => 'select',
          '#options' => $companion_options,
          '#default_value' => '_none',
          '#ajax' => array(
            'callback' => '_item_companions_pick',
            'wrapper' => 'vaxia-dice-companion',
            'method' => 'replace',
            'effect' => 'fade',
          ),
        );
        // Add companion dice roller.
        $form['vaxia_rolls']['companions'] = array(
          '#type' => 'fieldset',
          '#theme' => 'vaxia_dice_roller',
          '#prefix' => '<div id="vaxia-dice-companion" class="vaxia-dice-roller" style="display:none;">',
          '#suffix' => '</div>',
          '#weight' => 10,
          '#tree' => TRUE, // This is important, this allows the deltas below to function.
        );
        $companion = _item_companions_get_selected_companion($form, $form_state);
        if (!empty($companion)) {
          $form['vaxia_rolls']['companions'] = _vaxia_dice_roller_dice_form($companion, 'companion');
        }
        // Done.
      }
    }
  }
}

/**
 * Ajax callback for character selection.
 */
function _item_companions_pick($form, $form_state) {
  return isset($form['vaxia_rolls']['companions']) ? $form['vaxia_rolls']['companions'] : array();
}

/**
 * Implements hook_vaxia_dice_commands().
 */
function item_companions_vaxia_dice_commands_alter(&$rolls, $context) {
  $submitted_rolls = $context['submitted_rolls'];
  $character = $context['character'];
  $lang = $context['lang'];
  $companion_rolls = array();
  // Check for items.
  if (!empty($submitted_rolls['as_companion']) && !empty($submitted_rolls['companions'])) {
    // Make sure that the companion's roll is also included in the set.
    // So expanding the number of rolls and all.
    $companion = node_load($submitted_rolls['as_companion']);
    // Add rolls for the companion.
    foreach ($submitted_rolls['companions']['dice'] as $delta => $roll) {
      $number = !empty($roll['number']) ? $roll['number'] : 0;
      if ($number > 0) {
        $roll['size'] = !empty($roll['size']) ? $roll['size'] : 1;
        $roll['stat'] = ($roll['stat'] != -1) ? $roll['stat'] : 'any';
        $roll['skill'] = ($roll['skill'] != -1) ? $roll['skill'] : 0;
        $companion_rolls[] = $roll;
      }
    }
    // Calculate the companion roll preps.
    $companion_rolls = _vaxia_dice_roller_prep_rolls($companion_rolls, $companion, $lang);
    // Add the new rolls to the current rolls.
    $rolls = $rolls + $companion_rolls;
  }
}

/**
 * Implements hook_item_dice_submit_alter().
 */
function item_companions_item_dice_submit_alter(&$roll_mods, $context) {
  $lang = $context['lang'];
  $stat_key = $context['stat_key'];
  $item = $context['item'];
  $label = _item_companions_check($item);
  if (!empty($label)) {
    // This roll is Only for the roll as handled by the *character*.
    // Companions never modify the roll for the character, but we should add
    // them as an item note so that it's obvious the Companion is involved.
    // If we have a label add it only the once.
    // @todo - or skip the label at all.
    if (!empty($label) && $stat_key != 'skill') {
      $roll_mods[$stat_key]['notes'] .= ' ' . $item->title .' (' . $label . ')';
    }
  }
  return $roll_mods;
}

/**
 * Implements hook_item_dice_label().
 */
function item_companions_item_dice_label($item) {
  // Check for weapons if they exist.
  $labels = array();
  $companions = _item_companions_check($item);
  if (!empty($companions)) {
    $labels[] = $companions;
  }
  return $labels;
}

/**
 * Check if the item provides a weapon.
 */
function _item_companions_check($item, $both = TRUE) {
  //  Get item mod.
  $labels = array();
  // Weapon class.
  $item_type = isset($item->field_item_type[$item->language][0]['tid']) ?
    $item->field_item_type[$item->language][0]['tid'] : '';
  if (!empty($item_type)) {
    $item_type = taxonomy_term_load($item_type);
    // If this is listed as a companion / drone.
    if (!empty($item_type) && ($item_type->name == 'Companion/Drone')) {
      $labels[] = t('Companion');
    }
  }
  // Return the imploded set of labels.
  return implode(' ', $labels);
}

/**
 * Helper function, get the companion items.
 */
function _item_companions_get_companions($character) {
  $companions = array();
  if (isset($character->field_items[$character->language])) {
    foreach ($character->field_items[$character->language] as $delta => $nid) {
      $item = node_load($nid['nid']);
      if ($item && !empty($item->nid)) {
        $label = _item_companions_check($item);
        if (!empty($label)) {
          $companions[$item->nid] = $item;
        }
      }
    }
  }
  return $companions;
}

/**
 * Helper function get the selected companion.
 */
function _item_companions_get_selected_companion($form, $form_state) {
  $companion = '_none';
  // Check character selected from form.
  if(!empty($form_state['values']['vaxia_rolls']['as_companion'])) {
    $companion = $form_state['values']['vaxia_rolls']['as_companion'];
  }
  return $companion;
}
