<?php
/**
 * @file
 * Code for the Item usesƒ feature.
 */

/**
 * Implements hook_permission().
 */
function item_uses_permission() {
  return array(
    'use items indefinately' => array(
      'title' => t('use items indefinately'),
      'description' => t('Use items indefinately.'),
    ),
    'administer item uses' => array(
      'title' => t('administer item uses'),
      'description' => t('Administer item uses.'),
    ),
  );
}

/**
 * Implements hook_cron();
 */
function item_uses_cron() {
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  if (_vaxia_once_a_day_cron('item_uses_daily_recharge', '01:00:00')) {
    _item_uses_daily_recharge();
  }
}

/**
 * Implements hook_menu().
 */
function item_uses_menu() {
  $items['admin/vaxia/item_uses'] = array(
    'title' => 'Item uses configuration',
    'description' => 'Configure item uses',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_item_uses_admin_settings'),
    'access arguments' => array('administer item uses'),
  );
  return $items;
}

/**
 * Implementation of admin settings form.
 */
function _item_uses_admin_settings($form, &$form_state) {
  $form['item_uses_active'] = array(
    '#title' => t('Track item uses'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('item_uses_active', TRUE),
  );
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  $workflow_options = _vaxia_get_workflow_options();
  $form['item_uses_once_workflow'] = array(
    '#title' => 'Item used up',
    '#description' => 'Workflow state for items that need otbe recharged before they can be used again.',
    '#type' => 'select',
    '#options' => $workflow_options,
    '#default_value' => variable_get('item_uses_once_workflow', ''),
  );
  $form['item_uses_daily_workflow'] = array(
    '#title' => 'Item used for day',
    '#description' => 'Workflow state for items that need a reset day before they can be used again.',
    '#type' => 'select',
    '#options' => $workflow_options,
    '#default_value' => variable_get('item_uses_daily_workflow', ''),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_comment_insert().
 */
function item_uses_comment_insert($comment) {
  // If user has no dice roller, bail.
  if (!user_access('use dice roller')) {
    return;
  }
  // If not a dice roller type, bail.
  $node = node_load($comment->nid);
  $enabled = variable_get('dice_roller_' . $node->type, FALSE);
  if (!$enabled) {
    return;
  }
  _item_uses_content_update($comment);
}

/**
 * Called on hook_comment_insert().
 */
function _item_uses_content_update($comment) {
  // Allow for turning it all off.
  if (!variable_get('item_uses_active', TRUE) || user_access('use items indefinately') || empty($comment->vaxia_rolls)) {
    return;
  }
  $node = node_load($comment->nid);
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  if (!_vaxia_is_ic_room($node)) {
    return;
  }
  // Uses matter, so keep looping.
  $lang = $comment->language;
  // Check items against stats.
  if (isset($comment->vaxia_rolls['items'])) {
    // Gather the character information if it's set.
    $character = _vaxia_get_field_node($comment, 'field_comment_character');
    // If character set, get the stats and items.
    if (!empty($character)) {
      $once_workflow = variable_get('item_uses_once_workflow', '');
      $daily_workflow = variable_get('item_uses_daily_workflow', '');
      // Loop for each item.
      foreach ($comment->vaxia_rolls['items'] as $item) {
        _item_uses_check_item_use($item, $once_workflow, $daily_workflow);
      }
    }
  }
}

/**
 * Implements hook_item_dice_submit().
 */
function item_uses_item_dice_submit($items, $item, $stat_key, $lang) {
  $label = _item_uses_check($item);
  if (!empty($label)) {
    $notes = $item->title . ' ' . $label;
    $items[$stat_key]['general'] = isset($items[$stat_key]['general']) ? $items[$stat_key]['general'] : 0;
    $items[$stat_key]['notes'] = isset($items[$stat_key]['notes']) ? $items[$stat_key]['notes'] : '';
    $items[$stat_key]['notes'] .= ' ' . $notes;
    $items['any']['general'] = 0;
    $items['any']['notes'] = isset($items['any']['notes']) ? $items['any']['notes'] : '';
    $items['any']['notes'] .= ' ' . $notes;
  }
  return $items;
}

/**
 * Implements hook_item_dice_label().
 */
function item_uses_item_dice_label($item_labels, $item) {
  // Check for uses if they exist.
  $uses = _item_uses_check($item);
  if (!empty($uses)) {
    $item_labels[] = $uses;
  }
  return $item_labels;
}

/**
 * Check if the item provides a use.
 */
function _item_uses_check($item) {
  //  Get item mod.
  $label = '';
  $freq = isset($item->field_item_use_day[$item->language][0]['value']) ? $item->field_item_use_day[$item->language][0]['value'] : '';
  $pp = isset($item->field_pp_created[$item->language][0]['value']) ? $item->field_pp_created[$item->language][0]['value'] : '';
  $uses = isset($item->field_item_uses[$item->language][0]['value']) ? $item->field_item_uses[$item->language][0]['value'] : 0;
  $spent_uses = isset($item->field_item_spent_uses[$item->language][0]['value']) ? $item->field_item_spent_uses[$item->language][0]['value'] : 0;
  // Get all labels.
  $labels = array();
  if ($freq != 'at_will') {
    if ($freq == 'per_day') {
      $labels[] = 'Per Day';
    }
    else {
      $labels[] = 'Once';
    }
  }
  // Uses left.
  $uses_left = $uses - $spent_uses;
  if ($freq != 'at_will' && $uses_left > 0) {
    $labels[] = $uses_left . ' uses';
  }
  // PP amount.
  if ($pp > 0) {
    $labels[] = $pp . ' PP';
  }
  return implode(', ', $labels);
}

/**
 * Helper function, check the item use.
 */
function _item_uses_check_item_use($item, $once_workflow, $daily_workflow) {
  $item = node_load($item);
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  $uses = _vaxia_get_field_value($item, 'field_item_use_day', 'at_will');
  $charges = _vaxia_get_field_value($item, 'field_item_uses', 1);
  $spent_charges = _vaxia_get_field_value($item, 'field_item_spent_uses', 0);
  // Only subtract from uses for items that are individual use.
  if (in_array($uses, array('once', 'per_day')) && $charges > 0) {
    // Reduce uses.
    $spent_charges++;
    _vaxia_set_field_value($item, 'field_item_spent_uses', $spent_charges);
    drupal_set_message(t('@title charge used, @charges charges remaining.',
    array('@title' => $item->title, '@charges' => $charges - $spent_charges)));
    // If the item is out - note it and remove from play.
    if ($charges - $spent_charges <= 0) {
      if ($uses == 'once') {
        // For one time use.
        drupal_set_message(t('@title is out of uses cannot be used again until recharged.', array('@title' => $item->title)));
        workflow_execute_transition($item, $once_workflow, t('Item uses ran out, item temporarily removed from game.'), TRUE);
      }
      else {
        // For daily recharge use.
        drupal_set_message(t('@title is out of uses cannot be used again until tomorrow.', array('@title' => $item->title)));
        workflow_execute_transition($item, $daily_workflow, t('Item uses ran out, item temporarily removed from game.'), TRUE);
      }
    }
    // Save changes.
    node_save($item);
  } // end if $uses == 'once' uses > -1
}

/**
 * Helper function, get the cron for this run.
 */
function _item_uses_daily_recharge() {
  watchdog('item_uses', 'Daily recharge started.');
  // Make sure we have the vaxia helper file included.
  module_load_include('inc', 'vaxia', 'helper');
  $items = _vaxia_get_in_workflows(variable_get('item_uses_daily_workflow', ''));
  foreach ($items as $item) {
    $item = node_load($item->nid);
    if ($item) {
      $spent = _vaxia_get_field_value($item, 'field_item_spent_uses', 0);
      if ($spent > 0) {
        watchdog('item_uses', 'Daily recharge for item #' . $item->nid . '.');
        _vaxia_set_field_value($item, 'field_item_spent_uses', 0);
        $workflow = variable_get('items_approved_workflow', ''); // Set back to approved.
        workflow_execute_transition($item, $workflow, t('Item recharged daily.'), TRUE);
        node_save($item);
      }
    }
  }
}