<?php
/**
 * @file
 * Provide a vacation button for users to temp remove roles.
 */

/**
 * Implements hook_permission().
 */
function vacation_permission() {
  return array(
    'administer vacation'=> array(
      'title' => t('administer vacation'),
      'description' => t('Administer vacation.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function vacation_menu() {
  $items['admin/config/people/vacation'] = array(
    'title' => 'Vacation configurations',
    'description' => 'Vacation configurations',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer vacation'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vacation_admin_form'),
  );
  return $items;
}

/**
 * Menu callback for admin page.
 */
function vacation_admin_form() {
  $form = array();
  foreach (user_roles() as $rid => $name) {
    $roles[$name] = $name;
  }
  $form['vacation_roles'] = array(
    '#title' => t('Vacation roles'),
    '#type' => 'select',
    '#options' =>  $roles,
    '#default_value' => variable_get('vacation_roles', array()),
  );
  $default_message = t('<b>If you know you will be absent for some time: Please let us know! '.
    'We need to know if you\'ll be around or not.</b> <br/> When you go on vcation mode all of ' .
    'your additional permissions are removed. During this time you will not recieve emails, ' .
    'notifications, or other communications from the site and we won\'t expect you to perform ' .
    'duties. When you return, hit the button and your permissions will be returned to you.');
  $form['vacation_description'] = array(
    '#title' => t('Vacation descriptions'),
    '#type' => 'textarea',
    '#default_value' => variable_get('vacation_description', $default_message),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_rules_event_info().
 */
function vacation_rules_event_info() {
  $items = array(
    'vacation_start' => array(
      'label' => t('Vacation start'),
      'group' => t('Vacation'),
      'variables' => array(
        'user' => array(
            'type' => 'user',
            'label' => t('Vacation user'),
        ),
      ),
    ),
    'vacation_end' => array(
      'label' => t('Vacation end'),
      'group' => t('Vacation'),
      'variables' => array(
        'user' => array(
            'type' => 'user',
            'label' => t('Vacation user'),
        ),
      ),
    ),
  );
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vacation_form_user_profile_form_alter(&$form, &$form_state) {
  // If user account has any of the roles to watch for.
  $extra_roles = variable_get('vacation_roles', array());
  $default_message = variable_get('vacation_description', '');
  $has_extra = FALSE;
  foreach ($extra_roles as $extra_role) {
    if (in_array($extra_role, $form['#user']->roles)) {
      $has_extra = TRUE;
    }
  }
  // Get currently on vacation.
  $vacation_modes = variable_get('vacation', array());
  if ($has_extra == TRUE) {
    // Provide element.
    $form['vacation'] = array(
      '#type' => 'fieldset',
      '#title' => t('Vacation mode'),
      '#description' => $default_message,
      '#weight' => 1000,
    );
    $form['vacation']['vacation_uid'] = array(
      '#type' => 'hidden',
      '#value' => $form['#user']->uid,
    );
    $form['vacation']['vacation_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Go on vacation'),
    );
    $form['vacation']['vacation_submit']['#submit'][] = '_vacation_go_on_vacation';
  }
  if (isset($vacation_modes[$form['#user']->uid])) {
    // Provide element.
    $form['vacation'] = array(
      '#type' => 'fieldset',
      '#title' => t('Vacation mode'),
      '#description' => $default_message,
      '#weight' => 1000,
    );
    $form['vacation']['vacation_uid'] = array(
      '#type' => 'hidden',
      '#value' => $form['#user']->uid,
    );
    $form['vacation']['vacation_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Return from vacation'),
    );  
    $form['vacation']['vacation_submit']['#submit'][] = '_vacation_return_from_vacation';
  }
}

/**
 * Implements form submit handler.
 */
function _vacation_go_on_vacation(&$form, &$form_state) {
  $uid = $form_state['values']['vacation_uid'];
  $vacation_modes = variable_get('vacation', array());
  $account = user_load($uid);
  $vacation_modes[$uid] = $account->roles;
  variable_set('vacation', $vacation_modes);
  $role = user_role_load_by_name('player');
  $account->roles = array();
  $account->roles[$role->rid] = $role->name;
  _vacation_update_roles($account);
  if (function_exists('rules_invoke_event')) {
    rules_invoke_event('vacation_start', $account);
  }
}

/**
 * Implements form submit handler.
 */
function _vacation_return_from_vacation(&$form, &$form_state) {
  $uid = $form_state['values']['vacation_uid'];
  $vacation_modes = variable_get('vacation', array());
  if (isset($vacation_modes[$uid])) {
    $account = user_load($uid);
    $account->roles = $vacation_modes[$uid];
    unset($vacation_modes[$uid]);
    variable_set('vacation', $vacation_modes);
    _vacation_update_roles($account);
    if (function_exists('rules_invoke_event')) {
      rules_invoke_event('vacation_end', $account);
    }
  }
}

/**
 * Helper function update roles for given user.
 */
function _vacation_update_roles($account) {
  db_delete('users_roles')->condition('uid', $account->uid)->execute();
  $query = db_insert('users_roles')->fields(array('uid', 'rid'));
  foreach (array_keys($account->roles) as $rid) {
    if (!in_array($rid, array(DRUPAL_ANONYMOUS_RID, DRUPAL_AUTHENTICATED_RID))) {
      $query->values(array(
        'uid' => $account->uid,
        'rid' => $rid,
      ));
    }
  }
  $query->execute();
  drupal_session_destroy_uid($account->uid);
}