<?php
/**
 * @file
 * Provide a in-site dice ruler for helping to run sessions.
 */

/**
 * Implements hook_permission().
 */
function dice_ruler_permission() {
  return array(
    'use dice ruler'=> array(
      'title' => t('use dice ruler'),
      'description' => t('Use dice ruler.'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function dice_ruler_block_info() {
  $blocks['dice_ruler'] = array(
    'info' => t('Dice ruler'),
    'cache' => DRUPAL_NO_CACHE, // DRUPAL_CACHE_PER_ROLE
  );
  return $blocks;
}


/**
 * Implements hook_block_view($delta = '').
 */
function dice_ruler_block_view($delta = '') {
  if ($delta == 'dice_ruler') {
    $block = array(
      'subject' => t('Dice ruler'),
      'content' => drupal_get_form('dice_ruler_form'),
    );
  }
  return $block;
}

/**
 * Form callback for the dice ruler form.
 * Mostly ajax driven results.
 */
function dice_ruler_form($form, &$form_state) {
  $form = array();
  $form['dice_ruler_style'] = array(
    '#type' => 'item',
    '#markup' => '<style>' .
      '#dice-ruler-form table{margin-top:0px;}'.
      '#dice-ruler-form .form-type-textfield{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#dice-ruler-form .fieldset{margin-right:220px;}' .
      '#dice-ruler-form #dice_ruler_dice_results{margin-right:220px;} '.
      '#dice-ruler-form #dice_ruler_dice_results th{padding-left:0.5em;text-align:center;}'.
      '#dice-ruler-form #dice_ruler_dice_results td{padding-left:0.5em;text-align:center;}'.
      '#dice-ruler-form #edit-a--3{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#dice-ruler-form #edit-b--3{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#dice-ruler-form #dice_ruler_dice_help{float:right;clear:right;margin-top:1em;margin-left:1em;}'.
      '#dice-ruler-form #dice_ruler_dice_help{width:210px;}'.
      '#dice-ruler-form #dice_ruler_dice_help_2{float:right;clear:right;margin-top:1em;margin-left:1em;}'.
      '#dice-ruler-form #dice_ruler_dice_help_2{width:210px;}'.
      '#dice-ruler-form .form-item-combat-action-count-a, #dice-ruler-form .form-item-combat-action-count-b{float:left}' .
      '#dice-ruler-form .form-item-combat-weapon-a, #dice-ruler-form .form-item-combat-weapon-b{float:none; margin-left:65px;}' .
      '</style>',
  );

  $form['dice_ruler_dice_help'] = array(
    '#title' => t('Difficulty guidelines'),
    '#type' => 'item',
    '#markup' => '<ul>' . "\n" .
        '<li>1 to 10: Ridiculously easy.</li>' . "\n" .
        '<li>10 to 20: Easy.</li>' . "\n" .
        '<li>20 to 30: Normal.</li>' . "\n" .
        '<li>40 to 50: Skilled.</li>' . "\n" .
        '<li>60 to 70: Mastery.</li>' . "\n" .
       '<li>100 : Extremely Difficult.</li>' . "\n" .
        '</ul>',
    '#prefix' => '<div id="dice_ruler_dice_help">',
    '#suffix' => '</div>',
    '#states' => array(
      'invisible' => array(
        ':input[name="roll_type"]' => array('value' => 'hidden'),
      ),
    ),
  );
  $form['dice_ruler_dice_help_2'] = array(
    '#title' => t('Magic resistance skills'),
    '#type' => 'item',
    '#markup' => '<p>' .
        t('For magic: Most skills will not apply for pasively resisting a magical attack. If the target ' .
        'is actively resisting with a skill, roll and use their PP to counter the PP of the caster\'s roll. ' .
        'See !magic_url for more details.',
        array('!magic_url' => l('the magic rules', 'wiki/system-rules/ruling/magic-ruling'))) . 
        '</p>',
    '#prefix' => '<div id="dice_ruler_dice_help_2">',
    '#suffix' => '</div>',
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'magic'),
      ),
    ),
  );
  
  // Select a type.
  $form['roll_type'] = array(
    '#type' => 'select',
    '#title' => t('Roll type'),
    '#options' => array(
      'hidden' => t('Hide roller'),
      'one_trait' => t('One trait'),
      'two_trait' => t('Two trait'),
      'trait_vs' => t('Trait vs. trait'),
      'combat' => t('Combat'),
      'magic' => t('Magic'),
    ),
    '#default_value' => 'hidden',
  );

  // Subforms for each type of roll. One trait.
  $form['one_trait'] = array(
    '#type' => 'fieldset',
    '#title' => t('One trait'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'one_trait'),
      ),
    ),
  );
  $form['one_trait']['one_trait_might'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_diff'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_add_diff'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_rolled'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  // Two trait.
  $form['two_trait'] = array(
    '#type' => 'fieldset',
    '#title' => t('Two trait'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'two_trait'),
      ),
    ),
  );
  $form['two_trait']['a'] = array(
    '#type' => 'fieldset',
    '#title' => t('Trait A'),
  );
  $form['two_trait']['a']['two_trait_might_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['two_trait']['a']['two_trait_diff_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['two_trait']['a']['two_trait_add_diff_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['two_trait']['a']['two_trait_rolled_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['two_trait']['b'] = array(
    '#type' => 'fieldset',
    '#title' => t('Trait B'),
  );
  $form['two_trait']['b']['two_trait_might_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['two_trait']['b']['two_trait_diff_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['two_trait']['b']['two_trait_add_diff_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['two_trait']['b']['two_trait_rolled_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  // Subforms for each type of roll. One trait.
  $form['trait_vs'] = array(
    '#type' => 'fieldset',
    '#title' => t('One trait'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'trait_vs'),
      ),
    ),
  );
  $form['trait_vs']['a'] = array(
    '#type' => 'fieldset',
    '#title' => t('Character A'),
  );
  $form['trait_vs']['a']['trait_vs_might_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['trait_vs']['a']['trait_vs_add_diff_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['trait_vs']['a']['trait_vs_rolled_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['trait_vs']['b'] = array(
    '#type' => 'fieldset',
    '#title' => t('Character B'),
  );
  $form['trait_vs']['b']['trait_vs_might_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['trait_vs']['b']['trait_vs_add_diff_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['trait_vs']['b']['trait_vs_rolled_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  // Combat
  $form['combat'] = array(
    '#type' => 'fieldset',
    '#title' => t('Combat'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'combat'),
      ),
    ),
  );
  $form['combat']['a'] = array(
    '#type' => 'fieldset',
    '#title' => t('Character A'),
  );
  $form['combat']['a']['combat_action_count_a'] = array(
    '#type' => 'select',
    '#title' => t('Actions'),
    '#options' => array(
      '0' => '1',
      '20' => '2',
      '40' => '3',
      '60' => '4',
    ),
  );
  $form['combat']['a']['combat_weapon_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Weapon %'),
    '#size' => 5,
  );
  $form['combat']['a']['dex'] = array(
    '#type' => 'fieldset',
    '#title' => t('Dexterity'),
  );
  $form['combat']['a']['dex']['combat_might_a_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['a']['dex']['combat_add_diff_a_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['a']['dex']['combat_rolled_a_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['combat']['a']['str'] = array(
    '#type' => 'fieldset',
    '#title' => t('Strength'),
  );
  $form['combat']['a']['str']['combat_might_a_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['a']['str']['combat_add_diff_a_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['a']['str']['combat_rolled_a_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['combat']['a']['end'] = array(
    '#type' => 'fieldset',
    '#title' => t('Endurance'),
  );
  $form['combat']['a']['end']['combat_might_a_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['a']['end']['combat_add_diff_a_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['a']['end']['combat_rolled_a_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  $form['combat']['b'] = array(
    '#type' => 'fieldset',
    '#title' => t('Character B'),
  );
  $form['combat']['b']['combat_action_count_b'] = array(
    '#type' => 'select',
    '#title' => t('Actions'),
    '#options' => array(
      '0' => '1',
      '20' => '2',
      '40' => '3',
      '60' => '4',
    ),
  );
  $form['combat']['b']['combat_weapon_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Weapon %'),
    '#size' => 5,
  );
  $form['combat']['b']['dex'] = array(
    '#type' => 'fieldset',
    '#title' => t('Dexterity'),
  );
  $form['combat']['b']['dex']['combat_might_b_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['b']['dex']['combat_add_diff_b_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['b']['dex']['combat_rolled_b_dex'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['combat']['b']['str'] = array(
    '#type' => 'fieldset',
    '#title' => t('Strength'),
  );
  $form['combat']['b']['str']['combat_might_b_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['b']['str']['combat_add_diff_b_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['b']['str']['combat_rolled_b_str'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['combat']['b']['end'] = array(
    '#type' => 'fieldset',
    '#title' => t('Endurance'),
  );
  $form['combat']['b']['end']['combat_might_b_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['combat']['b']['end']['combat_add_diff_b_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['combat']['b']['end']['combat_rolled_b_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  // Magic
  $form['magic'] = array(
    '#type' => 'fieldset',
    '#title' => t('Magic'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'magic'),
      ),
    ),
  );
  $form['magic']['a'] = array(
    '#type' => 'fieldset',
    '#title' => t('Intelligence'),
  );
  $form['magic']['a']['magic_might_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['magic']['a']['magic_diff_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['magic']['a']['magic_add_diff_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['magic']['a']['magic_rolled_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['magic']['b'] = array(
    '#type' => 'fieldset',
    '#title' => t('Spirituality'),
  );
  $form['magic']['b']['magic_might_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['magic']['b']['magic_diff_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['magic']['b']['magic_add_diff_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['magic']['b']['magic_rolled_b'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );
  $form['magic']['target'] = array(
    '#type' => 'fieldset',
    '#title' => t('Target Resistance'),

  );
  $form['magic']['target']['magic_target_stat'] = array(
    '#type' => 'textfield',
    '#title' => t('Stat'),
    '#size' => 5,
  );
  $form['magic']['target']['magic_target_skill'] = array(
    '#type' => 'textfield',
    '#title' => t('Skill*'),
    '#size' => 5,
  );

  // Show results.
  $results = t('No roll performed.');
  if (!empty($form_state['values']['roll_type'])) {
    switch ($form_state['values']['roll_type']) {
      case 'one_trait':
        $results = _dice_ruler_one_trait(
          $form_state['values']['one_trait_might'],
          $form_state['values']['one_trait_diff'],
          $form_state['values']['one_trait_add_diff'],
          $form_state['values']['one_trait_rolled']
        );
      break;
      case 'two_trait':
        $results = _dice_ruler_two_trait(
          $form_state['values']['two_trait_might_a'],
          $form_state['values']['two_trait_diff_a'],
          $form_state['values']['two_trait_add_diff_a'],
          $form_state['values']['two_trait_rolled_a'],
          $form_state['values']['two_trait_might_b'],
          $form_state['values']['two_trait_diff_b'],
          $form_state['values']['two_trait_add_diff_b'],
          $form_state['values']['two_trait_rolled_b']
        );
      break;
      case 'trait_vs':
        $results = _dice_ruler_trait_vs(
          $form_state['values']['trait_vs_might_a'],
          $form_state['values']['trait_vs_add_diff_a'],
          $form_state['values']['trait_vs_rolled_a'],
          $form_state['values']['trait_vs_might_b'],
          $form_state['values']['trait_vs_add_diff_b'],
          $form_state['values']['trait_vs_rolled_b']
        );
      break;
      case 'combat':
        // Remove from mights based on action counts.
        $form_state['values']['combat_might_a_dex'] -= $form_state['values']['combat_action_count_a'];
        if ($form_state['values']['combat_might_a_dex'] < 0) {
          $form_state['values']['combat_might_a_dex'] = 0;
        }
        $form_state['values']['combat_might_a_str'] -= $form_state['values']['combat_action_count_a']; 
        if ($form_state['values']['combat_might_a_str'] < 0) {
          $form_state['values']['combat_might_a_str'] = 0;
        }
        $form_state['values']['combat_might_a_end'] -= $form_state['values']['combat_action_count_a']; 
        if ($form_state['values']['combat_might_a_end'] < 0) {
          $form_state['values']['combat_might_a_end'] = 0;
        }
        $form_state['values']['combat_might_b_dex'] -= $form_state['values']['combat_action_count_b'];
        if ($form_state['values']['combat_might_b_dex'] < 0) {
          $form_state['values']['combat_might_b_dex'] = 0;
        }
        $form_state['values']['combat_might_b_str'] -= $form_state['values']['combat_action_count_b']; 
        if ($form_state['values']['combat_might_b_str'] < 0) {
          $form_state['values']['combat_might_b_str'] = 0;
        }
        $form_state['values']['combat_might_b_end'] -= $form_state['values']['combat_action_count_b']; 
        if ($form_state['values']['combat_might_b_end'] < 0) {
          $form_state['values']['combat_might_b_end'] = 0;
        }

        // Get results.
        $results = _dice_ruler_combat(
          $form_state['values']['combat_might_a_dex'],
          $form_state['values']['combat_add_diff_a_dex'],
          $form_state['values']['combat_rolled_a_dex'],
          $form_state['values']['combat_might_a_str'],
          $form_state['values']['combat_add_diff_a_str'],
          $form_state['values']['combat_rolled_a_str'],
          $form_state['values']['combat_might_a_end'],
          $form_state['values']['combat_add_diff_a_end'],
          $form_state['values']['combat_rolled_a_end'],
          $form_state['values']['combat_weapon_a'],

          $form_state['values']['combat_might_b_dex'],
          $form_state['values']['combat_add_diff_b_dex'],
          $form_state['values']['combat_rolled_b_dex'],
          $form_state['values']['combat_might_b_str'],
          $form_state['values']['combat_add_diff_b_str'],
          $form_state['values']['combat_rolled_b_str'],
          $form_state['values']['combat_might_b_end'],
          $form_state['values']['combat_add_diff_b_end'],
          $form_state['values']['combat_rolled_b_end'],
          $form_state['values']['combat_weapon_b']
        );
      break;
      case 'magic':
        $results = _dice_ruler_magic(
          $form_state['values']['magic_might_a'],
          $form_state['values']['magic_diff_a'],
          $form_state['values']['magic_add_diff_a'],
          $form_state['values']['magic_rolled_a'],
          $form_state['values']['magic_might_b'],
          $form_state['values']['magic_diff_b'],
          $form_state['values']['magic_add_diff_b'],
          $form_state['values']['magic_rolled_b'],
          $form_state['values']['magic_target_stat'],
          $form_state['values']['magic_target_skill']
        );
      break;
    }
  }

  $form['dice_ruler_dice_results'] = array(
    '#title' => t('Roll results'),
    '#type' => 'item',
    '#markup' => $results,
    '#prefix' => '<div id="dice_ruler_dice_results">',
    '#suffix' => '</div>',
    '#states' => array(
      'invisible' => array(
        ':input[name="roll_type"]' => array('value' => 'hidden'),
      ),
    ),
  );

  // Provide button.
  $form['rule_dice'] = array(
    '#type' => 'button',
    '#value' => t('Rule roll'),
    '#ajax' => array(
      'callback' => 'dice_ruler_form_ajax',
      'wrapper' => 'dice_ruler_dice_results',
      'method' => 'replace',
      'effect' => 'fade',
    ),
    '#states' => array(
      'invisible' => array(
        ':input[name="roll_type"]' => array('value' => 'hidden'),
      ),
    ),
  );
  
  // Attach the JS for this ruler to pick up results from the chatroom.
  drupal_add_js(drupal_get_path('module', 'dice_ruler') . '/js/dice_ruler.js');
  return $form;
}

/**
 * AJAX callback for ruling form.
 */
function dice_ruler_form_ajax($form, $form_state) {
  return $form['dice_ruler_dice_results'];
}

/**
 * Handle ruling for one trait.
 */
function _dice_ruler_one_trait(
  $one_trait_might = 50,
  $one_trait_diff = 50,
  $one_trait_add_diff = 0,
  $one_trait_rolled = 50
) {

  // Check that all are numeric.
  if (!empty($one_trait_might) && !is_numeric($one_trait_might)
    || !empty($one_trait_diff) && !is_numeric($one_trait_diff)
    || !empty($one_trait_add_diff) && !is_numeric($one_trait_add_diff)
    || !empty($one_trait_rolled) && !is_numeric($one_trait_rolled)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($one_trait_might)
    || empty($one_trait_diff)
    || empty($one_trait_rolled)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($one_trait_add_diff)) {
    $one_trait_add_diff = 0;
  }

  // Get results from our master function.
  $results = _dice_ruler_make_ruling(
  $one_trait_might,
  $one_trait_diff,
  $one_trait_add_diff,
  $one_trait_rolled);

  // Now put all these into a table to display.
  $header = array(
    t('Might'),
    t('Diff'),
    t('Add diff.'),
    t('Rolled'),
    t('Roll needed'),
    t('Success'),
    t('Winsby'),
    t('Points'),
    t('% of diff'),
    t('Failed might'),
  );
  $rows[] = $results;
  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
  ));
  return $output;
}

/**
 * Handle ruling for two trait.
 */
function _dice_ruler_two_trait(
  $two_trait_might_a,
  $two_trait_diff_a,
  $two_trait_add_diff_a,
  $two_trait_rolled_a,
  $two_trait_might_b,
  $two_trait_diff_b,
  $two_trait_add_diff_b,
  $two_trait_rolled_b
) {

  // Check that all are numeric.
  if (!empty($two_trait_might_a) && !is_numeric($two_trait_might_a)
    || !empty($two_trait_diff_a) && !is_numeric($two_trait_diff_a)
    || !empty($two_trait_add_diff_a) && !is_numeric($two_trait_add_diff_a)
    || !empty($two_trait_rolled_a) && !is_numeric($two_trait_rolled_a)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($two_trait_might_a)
    || empty($two_trait_diff_a)
    || empty($two_trait_rolled_a)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($two_trait_add_diff_a)) {
    $two_trait_add_diff_a = 0;
  }

  // Check that all are numeric.
  if (!empty($two_trait_might_b) && !is_numeric($two_trait_might_b)
    || !empty($two_trait_diff_b) && !is_numeric($two_trait_diff_b)
    || !empty($two_trait_add_diff_b) && !is_numeric($two_trait_add_diff_b)
    || !empty($two_trait_rolled_b) && !is_numeric($two_trait_rolled_b)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($two_trait_might_b)
    || empty($two_trait_diff_b)
    || empty($two_trait_rolled_b)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($two_trait_add_diff_b)) {
    $two_trait_add_diff_b = 0;
  }

  $results = _dice_ruler_make_two_trait_ruling(
    $two_trait_might_a,
    $two_trait_diff_a,
    $two_trait_add_diff_a,
    $two_trait_rolled_a,
    $two_trait_might_b,
    $two_trait_diff_b,
    $two_trait_add_diff_b,
    $two_trait_rolled_b
  );

  // Now put all these into a table to display.
  $header = array(
    t('Might'),
    t('Diff'),
    t('Add diff.'),
    t('Rolled'),
    t('Roll needed'),
    t('Success'),
    t('Winsby'),
    t('Points'),
    t('% of diff'),
    t('Failed might'),
  );
  $rows[] = $results;
  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
  ));
  return $output;
}

/**
 * Handle ruling for trait vs.
 */
function _dice_ruler_trait_vs(
  $trait_vs_might_a,
  $trait_vs_add_diff_a,
  $trait_vs_rolled_a,
  $trait_vs_might_b,
  $trait_vs_add_diff_b,
  $trait_vs_rolled_b
) {

  // Check that all are numeric.
  if (!empty($trait_vs_might_a) && !is_numeric($trait_vs_might_a)
    || !empty($trait_vs_add_diff_a) && !is_numeric($trait_vs_add_diff_a)
    || !empty($trait_vs_rolled_a) && !is_numeric($trait_vs_rolled_a)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($trait_vs_might_a)
    || empty($trait_vs_rolled_a)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($trait_vs_add_diff_a)) {
    $trait_vs_add_diff_a = 0;
  }

  // Check that all are numeric.
  if (!empty($trait_vs_might_b) && !is_numeric($trait_vs_might_b)
    || !empty($trait_vs_add_diff_b) && !is_numeric($trait_vs_add_diff_b)
    || !empty($trait_vs_rolled_b) && !is_numeric($trait_vs_rolled_b)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($trait_vs_might_b)
    || empty($trait_vs_rolled_b)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($trait_vs_add_diff_b)) {
    $trait_vs_add_diff_b = 0;
  }

  // Get results from our master function.
  $results = _dice_ruler_make_ruling(
  $trait_vs_might_a,
  $trait_vs_might_b,
  $trait_vs_add_diff_a,
  $trait_vs_rolled_a);
  $rows[] = $results;

  // Second roll.
  $results = _dice_ruler_make_ruling(
  $trait_vs_might_b,
  $trait_vs_might_a,
  $trait_vs_add_diff_b,
  $trait_vs_rolled_b);
  $rows[] = $results;

  // Now put all these into a table to display.
  $header = array(
    t('Might'),
    t('Diff'),
    t('Add diff.'),
    t('Rolled'),
    t('Roll needed'),
    t('Success'),
    t('Winsby'),
    t('Points'),
    t('% of diff'),
    t('Failed might'),
  );  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
  ));
  return $output;
}

/**
 * Handle ruling for combat.
 */
function _dice_ruler_combat(
  $combat_might_a_dex,
  $combat_add_diff_a_dex,
  $combat_rolled_a_dex,
  $combat_might_a_str,
  $combat_add_diff_a_str,
  $combat_rolled_a_str,
  $combat_might_a_end,
  $combat_add_diff_a_end,
  $combat_rolled_a_end,
  $combat_weapon_a,

  $combat_might_b_dex,
  $combat_add_diff_b_dex,
  $combat_rolled_b_dex,
  $combat_might_b_str,
  $combat_add_diff_b_str,
  $combat_rolled_b_str,
  $combat_might_b_end,
  $combat_add_diff_b_end,
  $combat_rolled_b_end,
  $combat_weapon_b
) {

  // Check that all are numeric.
  if (!empty($combat_might_a_dex) && !is_numeric($combat_might_a_dex)
    || !empty($combat_add_diff_a_dex) && !is_numeric($combat_add_diff_a_dex)
    || !empty($combat_rolled_a_dex) && !is_numeric($combat_rolled_a_dex)
    || !empty($combat_might_a_str) && !is_numeric($combat_might_a_str)
    || !empty($combat_add_diff_a_str) && !is_numeric($combat_add_diff_a_str)
    || !empty($combat_rolled_a_str) && !is_numeric($combat_rolled_a_str)
    || !empty($combat_might_a_end) && !is_numeric($combat_might_a_end)
    || !empty($combat_add_diff_a_end) && !is_numeric($combat_add_diff_a_end)
    || !empty($combat_rolled_a_end) && !is_numeric($combat_rolled_a_end)
    || !empty($combat_weapon_a) && !is_numeric($combat_weapon_a)
    ) {
    return t('Not all values given were numeric. We need numbers for math.');
  }

  // Check our required values are set.
  if (empty($combat_might_a_dex)
    || empty($combat_rolled_a_dex)
    || empty($combat_might_a_str)
    || empty($combat_rolled_a_str)
    || empty($combat_might_a_end)
    || empty($combat_rolled_a_end)) {
    return t('Not all required values given.');
  }

  // Set default if empty.
  if (empty($combat_add_diff_a_dex)) {
    $combat_add_diff_a_dex = 0;
  }
  if (empty($combat_add_diff_a_str)) {
    $combat_add_diff_a_str = 0;
  }
  if (empty($combat_add_diff_a_end)) {
    $combat_add_diff_a_end = 0;
  }

  // Check that all are numeric.
  if (!empty($combat_might_b_dex) && !is_numeric($combat_might_b_dex)
    || !empty($combat_add_diff_b_dex) && !is_numeric($combat_add_diff_b_dex)
    || !empty($combat_rolled_b_dex) && !is_numeric($combat_rolled_b_dex)
    || !empty($combat_might_b_str) && !is_numeric($combat_might_b_str)
    || !empty($combat_add_diff_b_str) && !is_numeric($combat_add_diff_b_str)
    || !empty($combat_rolled_b_str) && !is_numeric($combat_rolled_b_str)
    || !empty($combat_might_b_end) && !is_numeric($combat_might_b_end)
    || !empty($combat_add_diff_b_end) && !is_numeric($combat_add_diff_b_end)
    || !empty($combat_rolled_b_end) && !is_numeric($combat_rolled_b_end)
    || !empty($combat_weapon_b) && !is_numeric($combat_weapon_b)
    ) {
    return t('Not all values given were numeric. We need numbers for math.');
  }

  // Check our required values are set.
  if (!isset($combat_might_b_dex)
    || !isset($combat_rolled_b_dex)
    || !isset($combat_might_b_str)
    || !isset($combat_rolled_b_str)
    || !isset($combat_might_b_end)
    || !isset($combat_rolled_b_end)) {
    return t('Not all required values given.');
  }

  // Set default if empty.
  if (empty($combat_add_diff_b_dex)) {
    $combat_add_diff_b_dex = 0;
  }
  if (empty($combat_add_diff_b_str)) {
    $combat_add_diff_b_str = 0;
  }
  if (empty($combat_add_diff_b_end)) {
    $combat_add_diff_b_end = 0;
  }

  // Prepare weapon combat damages
  if (empty($combat_weapon_a)) {
    $combat_weapon_a = 0;
  }
  elseif($combat_weapon_a > 1)  {
    $combat_weapon_a = $combat_weapon_a / 100;
  }
  if (empty($combat_weapon_b)) {
    $combat_weapon_b = 0;
  }
  elseif($combat_weapon_b > 1)  {
    $combat_weapon_b = $combat_weapon_b / 100;
  }

  $attack_a_vs_b = _dice_ruler_make_two_trait_ruling(
    $combat_might_a_dex,
    $combat_might_b_dex, // Defender.
    $combat_add_diff_a_dex,
    $combat_rolled_a_dex,
    $combat_might_a_str,
    $combat_might_b_end, // Defender.
    $combat_add_diff_a_str,
    $combat_rolled_a_str
  );
  array_unshift($attack_a_vs_b, 'A Attacks B:');
  $remove_field = array_pop($attack_a_vs_b);
  $remove_field = array_pop($attack_a_vs_b);
  $attack_a_vs_b[] = ($attack_a_vs_b[8] + ($attack_a_vs_b[8] * $combat_weapon_a)) . t(' to B, w/ weapon');
  $rows[] = $attack_a_vs_b;
  $attack_b_vs_a = _dice_ruler_make_two_trait_ruling(
    $combat_might_b_dex,
    $combat_might_a_dex, // Defender.
    $combat_add_diff_b_dex,
    $combat_rolled_b_dex,
    $combat_might_b_str,
    $combat_might_a_end, // Defender.
    $combat_add_diff_b_str,
    $combat_rolled_b_str
  );
  array_unshift($attack_b_vs_a, 'B Attacks A:');
  $remove_field = array_pop($attack_b_vs_a);
  $remove_field = array_pop($attack_b_vs_a);
  $attack_b_vs_a[] = ($attack_b_vs_a[8] + ($attack_b_vs_a[8] * $combat_weapon_b)) . t(' to A, w/ weapon');
  $rows[] = $attack_b_vs_a;
  $attack_a_points = $attack_a_vs_b[8]; // PP produced by a
  $attack_b_points = $attack_b_vs_a[8]; // PP produced by b

  $block_a_vs_b = _dice_ruler_make_two_trait_ruling(
    $combat_might_a_str,
    $combat_might_b_dex, // Defender.
    $combat_add_diff_a_str,
    $combat_rolled_a_str,
    $combat_might_a_end,
    $combat_might_b_str, // Defender.
    $combat_add_diff_a_end,
    $combat_rolled_a_end
  );
  array_unshift($block_a_vs_b, 'A Blocks B:');
  $remove_field = array_pop($block_a_vs_b);
  $remove_field = array_pop($block_a_vs_b);
  $block_a_vs_b[] = (($attack_b_points - $block_a_vs_b[8]) > 0) ?
    ($attack_b_points - $block_a_vs_b[8] + (($attack_b_points - $block_a_vs_b[8]) * $combat_weapon_b)) . t(' to A, w/ weapon') : 0 . t(' to A');
  $rows[] = $block_a_vs_b;
  $block_b_vs_a = _dice_ruler_make_two_trait_ruling(
    $combat_might_b_str,
    $combat_might_a_dex, // Defender.
    $combat_add_diff_b_str,
    $combat_rolled_b_str,
    $combat_might_b_end,
    $combat_might_a_str, // Defender.
    $combat_add_diff_b_end,
    $combat_rolled_b_end
  );
  array_unshift($block_b_vs_a, 'B Blocks A:');
  $remove_field = array_pop($block_b_vs_a);
  $remove_field = array_pop($block_b_vs_a);
  $block_b_vs_a[] = (($attack_a_points - $block_b_vs_a[8]) > 0) ?
    ($attack_a_points - $block_b_vs_a[8] + (($attack_a_points - $block_b_vs_a[8]) * $combat_weapon_a)) . t(' to B, w/ weapon') : 0 . t(' to B');
  $rows[] = $block_b_vs_a;
  
  $parry_a_vs_b = _dice_ruler_make_two_trait_ruling(
    $combat_might_a_dex,
    $combat_might_b_dex, // Defender.
    $combat_add_diff_a_dex,
    $combat_rolled_a_dex,
    $combat_might_a_str,
    $combat_might_b_str, // Defender.
    $combat_add_diff_a_str,
    $combat_rolled_a_str
  );
  array_unshift($parry_a_vs_b, 'A Parrys B:');
  $remove_field = array_pop($parry_a_vs_b);
  $remove_field = array_pop($parry_a_vs_b);
  $parry_a_vs_b[] = (($attack_b_points - $parry_a_vs_b[8]) > 0) ?
    ($attack_b_points - $parry_a_vs_b[8] + (($attack_b_points - $parry_a_vs_b[8]) * $combat_weapon_b)) . t(' to A, w/ weapon') : 0 . t(' to A');
  $rows[] = $parry_a_vs_b;
  $parry_b_vs_a = _dice_ruler_make_two_trait_ruling(
    $combat_might_b_dex,
    $combat_might_a_dex, // Defender.
    $combat_add_diff_b_dex,
    $combat_rolled_b_dex,
    $combat_might_b_str,
    $combat_might_a_str, // Defender.
    $combat_add_diff_b_str,
    $combat_rolled_b_str
  );
  array_unshift($parry_b_vs_a, 'B Parrys A:');
  $remove_field = array_pop($parry_b_vs_a);
  $remove_field = array_pop($parry_b_vs_a);
  $parry_b_vs_a[] = (($attack_a_points - $parry_b_vs_a[8]) > 0) ?
    ($attack_a_points - $parry_b_vs_a[8] + (($attack_a_points - $parry_b_vs_a[8]) * $combat_weapon_a)) . t(' to B, w/ weapon') : 0 . t(' to B');
  $rows[] = $parry_b_vs_a;
  
  $dodge_a_vs_b = _dice_ruler_make_two_trait_ruling(
    $combat_might_a_dex,
    $combat_might_b_dex, // Defender.
    $combat_add_diff_a_dex,
    $combat_rolled_a_dex,
    $combat_might_a_end,
    $combat_might_b_str, // Defender.
    $combat_add_diff_a_end,
    $combat_rolled_a_end
  );
  array_unshift($dodge_a_vs_b, 'A Dodges B:');
  $remove_field = array_pop($dodge_a_vs_b);
  $remove_field = array_pop($dodge_a_vs_b);
  $dodge_a_vs_b[] = (($attack_b_points - $dodge_a_vs_b[8]) > 0) ?
    ($attack_b_points - $dodge_a_vs_b[8] + (($attack_b_points - $dodge_a_vs_b[8]) * $combat_weapon_b)) . t(' to A, w/ weapon') : 0 . t(' to A');
  $rows[] = $dodge_a_vs_b;
  $dodge_b_vs_a = _dice_ruler_make_two_trait_ruling(
    $combat_might_b_dex,
    $combat_might_a_dex, // Defender.
    $combat_add_diff_b_dex,
    $combat_rolled_b_dex,
    $combat_might_b_end,
    $combat_might_a_str, // Defender.
    $combat_add_diff_b_end,
    $combat_rolled_b_end
  );
  array_unshift($dodge_b_vs_a, 'B Dodges A:');
  $remove_field = array_pop($dodge_b_vs_a);
  $remove_field = array_pop($dodge_b_vs_a);
  $dodge_b_vs_a[] = (($attack_a_points - $dodge_b_vs_a[8]) > 0) ?
    ($attack_a_points - $dodge_b_vs_a[8] + (($attack_a_points - $dodge_b_vs_a[8]) * $combat_weapon_a)) . t(' to B, w/ weapon') : 0 . t(' to B');
  $rows[] = $dodge_b_vs_a;
  // Now put all these into a table to display.
  $header = array(
    t('Action'),
    t('Might'),
    t('Diff'),
    t('Add diff.'),
    t('Rolled'),
    t('Roll needed'),
    t('Success'),
    t('Winsby'),
    t('Points'),
    t('After defense'),
  );  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
  ));
  return $output;
}

/**
 * Handle ruling for magic.
 */
function _dice_ruler_magic(
  $magic_might_a,
  $magic_diff_a,
  $magic_add_diff_a,
  $magic_rolled_a,
  $magic_might_b,
  $magic_diff_b,
  $magic_add_diff_b,
  $magic_rolled_b,
  $magic_target_stat,
  $magic_target_skill
) {
  // How this normally works.
  // Add the difficulty for the casting to the target stat.
  // And figure out if the target was affected...
  // Check that all are numeric.
  if (!empty($magic_might_a) && !is_numeric($magic_might_a)
    || !empty($magic_diff_a) && !is_numeric($magic_diff_a)
    || !empty($magic_add_diff_a) && !is_numeric($magic_add_diff_a)
    || !empty($magic_rolled_a) && !is_numeric($magic_rolled_a)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($magic_might_a)
    || empty($magic_diff_a)
    || empty($magic_rolled_a)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($magic_add_diff_a)) {
    $magic_add_diff_a = 0;
  }

  // Check that all are numeric.
  if (!empty($magic_might_b) && !is_numeric($magic_might_b)
    || !empty($magic_diff_b) && !is_numeric($magic_diff_b)
    || !empty($magic_add_diff_b) && !is_numeric($magic_add_diff_b)
    || !empty($magic_rolled_b) && !is_numeric($magic_rolled_b)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }
  // Check our required values are set.
  if (empty($magic_might_b)
    || empty($magic_diff_b)
    || empty($magic_rolled_b)) {
    return t('Not all required values given.');
  }
  // Set default if empty.
  if (empty($magic_add_diff_b)) {
    $magic_add_diff_b = 0;
  }

  // Set defaults for the target.
  if (empty($magic_target_stat)) {
    $magic_target_stat = 0;
  }
  if (empty($magic_target_skill)) {
    $magic_target_skill = 0;
  }

  // Check that all are numeric.
  if (!empty($magic_target_stat) && !is_numeric($magic_target_stat)
    || !empty($magic_target_skill) && !is_numeric($magic_target_skill)) {
    return t('Not all values given were numeric. We need numbers for math.');
  }

  // Now put all these into a table to display.
  $header = array(
    t('Might'),
    t('Diff'),
    t('Add diff.'),
    t('Rolled'),
    t('Roll needed'),
    t('Success'),
    t('Winsby'),
    t('Points'),
    t('% of diff'),
    t('Failed might'),
  );

  // Combine results.
  $rows = array();
  $results = _dice_ruler_make_magic_ruling(
    $magic_might_a,
    $magic_diff_a,
    $magic_add_diff_a,
    $magic_rolled_a,
    $magic_might_b,
    $magic_diff_b,
    $magic_add_diff_b,
    $magic_rolled_b);
  $rows[] = $results;

  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
  ));

  if ($magic_target_stat != 0 || $magic_target_skill != 0) {
    $output .= '<div><b>' . t('Resisted roll results') . ':</b></div>';
  
    // Set the target diffs for resisted.
    $magic_diff_a = $magic_diff_a + $magic_target_stat + $magic_target_skill;
    $magic_diff_b = $magic_diff_b + $magic_target_stat + $magic_target_skill;
    $output .= '<div>' . t('With target\'s resistance, the difficulty is') .': '. $magic_diff_a .  ' / ' . $magic_diff_b . '</div>';

    // Combine results.
    $rows = array();
    $results = _dice_ruler_make_magic_ruling(
      $magic_might_a,
      $magic_diff_a,
      $magic_add_diff_a,
      $magic_rolled_a,
      $magic_might_b,
      $magic_diff_b,
      $magic_add_diff_b,
      $magic_rolled_b);
    $rows[] = $results;
  
    $output .= theme('table', array(
      'header' => $header,
      'rows' => $rows,
    ));
  }

  return $output;
}

function _dice_ruler_make_magic_ruling(
  $magic_might_a,
  $magic_diff_a,
  $magic_add_diff_a,
  $magic_rolled_a,
  $magic_might_b,
  $magic_diff_b,
  $magic_add_diff_b,
  $magic_rolled_b) {

  // Change difficulty for dynamic difs.
  $magic_diff_a = 2 * ($magic_diff_a + $magic_add_diff_a) - ($magic_might_a);
  if ($magic_diff_a < 1) {
    $magic_diff_a = 1;
  }
  $magic_diff_b = 2 * ($magic_diff_b + $magic_add_diff_b) - ($magic_might_b);
  if ($magic_diff_b < 1) {
    $magic_diff_b = 1;
  }

  // Get results from our master function.
  $magic_a = _dice_ruler_make_ruling(
  $magic_might_a,
  $magic_diff_a,
  0,
  $magic_rolled_a);

  $magic_b = _dice_ruler_make_ruling(
  $magic_might_b,
  $magic_diff_b,
  0,
  $magic_rolled_b);

  $versus_one = (($magic_rolled_a - $magic_a[4]) >= 0) ? $magic_add_diff_a : 0; // 4 => Roll needed
  $versus_two = (($magic_rolled_b - $magic_b[4]) >= 0) ? $magic_add_diff_b : 0; // 4 => Roll needed
  $winsby_one = $magic_a[3] - $magic_a[4];
  $winsby_two = $magic_b[3] - $magic_b[4];
  $magic_winsby = ($winsby_one / 2) + ($winsby_two / 2) + $versus_one + $versus_two; // 6 => Windsby
  $magic_success = ($magic_winsby >= 0) ? 'yes' : 'no';
  if ($magic_success == 'no') {
    $magic_success = ($magic_winsby < -50) ? 'mishap' : 'no';
  }
  $magic_points = ($magic_winsby >= 0) ? ($magic_might_a + $magic_might_b) / 2 * $magic_winsby / 100 : 0;
  $magic_perc_diff = 'n/a';
  if ($magic_success != 'yes') {
    $magic_diff_perc_a = $magic_might_a * ((tan(($magic_rolled_a - 50.5) / 49.5 * atan(0.06 * 50)) / 6 + 0.5) / (0.5 - tan(($magic_rolled_a - 50.5) / 49.5 * atan(0.06 * 50)) / 6));
    $magic_diff_perc_b = $magic_might_b * ((tan(($magic_rolled_b - 50.5) / 49.5 * atan(0.06 * 50)) / 6 + 0.5) / (0.5 - tan(($magic_rolled_b - 50.5) / 49.5 * atan(0.06 * 50)) / 6));
    $magic_perc_diff = (($magic_diff_perc_a / $magic_diff_a) + ($magic_diff_perc_b / $magic_diff_b)) / 2;
  }
  $magic_failed_might = 0;
  if ($magic_success != 'yes') {
    $magic_failed_might = round((($magic_diff_a + $magic_diff_b) / 2) * (1 - $magic_perc_diff));
  }

  return array(
    '<div>' . $magic_might_a . '</div><div style="border-top:1px solid;">' . $magic_might_b . '</div>', // Display the two.
    '<div>' . $magic_diff_a . '</div><div style="border-top:1px solid;">' . $magic_diff_b . '</div>', // Display the two.
    '<div>' . $magic_add_diff_a . '</div><div style="border-top:1px solid;">' . $magic_add_diff_b . '</div>', // Display the two.
    '<div>' . $magic_rolled_a . '</div><div style="border-top:1px solid;">' . $magic_rolled_b . '</div>', // Display the two.
    '<div>' . number_format($magic_a[4], 1) . '</div><div style="border-top:1px solid;">' . number_format($magic_b[4], 1) . '</div>', // Display the two.
    $magic_success,
    is_numeric($magic_winsby) ? number_format($magic_winsby) : $magic_winsby,
    is_numeric($magic_points) ? number_format($magic_points) : $magic_points,
    is_numeric($magic_perc_diff) ? number_format($magic_perc_diff, 2) : $magic_perc_diff,
    $magic_failed_might,
  );
}

/**
 * Helper function, make a roll.
 */
function _dice_ruler_make_ruling(
  $one_trait_might,
  $one_trait_diff,
  $one_trait_add_diff,
  $one_trait_rolled
) {

  // The ladder is an eyeball. This is a gemoetric solution. I hope you like trig.
  $roll_needed = 50.5 + atan(0.06 * (100 * ($one_trait_diff + $one_trait_add_diff) / ($one_trait_diff + $one_trait_add_diff + $one_trait_might) - 50)) * 49.5 / atan(0.06 * 50);
  $success = ($one_trait_rolled < $roll_needed) ? 'no' : 'yes';
  $winsby_diff = (($one_trait_rolled - $roll_needed) >= 0 ) ? $one_trait_add_diff : 0;
  $winsby = ($one_trait_rolled - $roll_needed ) + $winsby_diff;
  $points = 0;
  if ($success == 'yes') {
    $points = $one_trait_might * ( $winsby / 100);
  }
  $perc_diff = 'n/a';
  if ($success == 'no') {
    $diff_perc = $one_trait_might * ((tan(($one_trait_rolled - 50.5) / 49.5 * atan(0.06 * 50)) / 6 + 0.5) / (0.5 - tan(($one_trait_rolled - 50.5) / 49.5 * atan(0.06 * 50)) / 6));
    $perc_diff = 0;
    if ($one_trait_diff != 0) {
      $perc_diff = $diff_perc / $one_trait_diff;
    }
  }
  $failed_might = 0;
  if ($success == 'no') {
    $failed_might = round($one_trait_diff * (1 - $perc_diff));
  }

  // Return array results.
  return array(
    $one_trait_might,
    $one_trait_diff,
    $one_trait_add_diff,
    $one_trait_rolled,
    $roll_needed,
    $success,
    $winsby,
    $points,
    is_numeric($perc_diff) ? number_format($perc_diff, 2) : $perc_diff,
    $failed_might,
  );
}

/**
 * Helper function, make a roll.
 */
function _dice_ruler_make_two_trait_ruling(
    $two_trait_might_a,
    $two_trait_diff_a,
    $two_trait_add_diff_a,
    $two_trait_rolled_a,
    $two_trait_might_b,
    $two_trait_diff_b,
    $two_trait_add_diff_b,
    $two_trait_rolled_b
) {

  // Get results from our master function.
  $trait_a = _dice_ruler_make_ruling(
  $two_trait_might_a,
  $two_trait_diff_a,
  $two_trait_add_diff_a,
  $two_trait_rolled_a);

  $trait_b = _dice_ruler_make_ruling(
  $two_trait_might_b,
  $two_trait_diff_b,
  $two_trait_add_diff_b,
  $two_trait_rolled_b);

  $versus_one = (($two_trait_rolled_a - $trait_a[4]) >= 0) ? $two_trait_add_diff_a : 0; // 4 => Roll needed
  $versus_two = (($two_trait_rolled_b - $trait_b[4]) >= 0) ? $two_trait_add_diff_b : 0; // 4 => Roll needed
  $winsby_one = $trait_a[3] - $trait_a[4];
  $winsby_two = $trait_b[3] - $trait_b[4];
  $two_trait_winsby = ($winsby_one / 2) + ($winsby_two / 2) + $versus_one + $versus_two; // 6 => Windsby
  $two_trait_success = ($two_trait_winsby >= 0) ? 'yes' : 'no';
  if ($two_trait_success == 'no') {
    $two_trait_success = ($two_trait_winsby < -50) ? 'mishap' : 'no';
  }
  $two_trait_points = ($two_trait_winsby >= 0) ? ($two_trait_might_a + $two_trait_might_b) / 2 * $two_trait_winsby / 100 : 0;
  $two_trait_perc_diff = 'n/a';
  if ($two_trait_success != 'yes') {
    $two_trait_diff_perc_a = $two_trait_might_a * ((tan(($two_trait_rolled_a - 50.5) / 49.5 * atan(0.06 * 50)) / 6 + 0.5) / (0.5 - tan(($two_trait_rolled_a - 50.5) / 49.5 * atan(0.06 * 50)) / 6));
    $two_trait_diff_perc_b = $two_trait_might_b * ((tan(($two_trait_rolled_b - 50.5) / 49.5 * atan(0.06 * 50)) / 6 + 0.5) / (0.5 - tan(($two_trait_rolled_b - 50.5) / 49.5 * atan(0.06 * 50)) / 6));
    $two_trait_perc_diff = (($two_trait_diff_perc_a / $two_trait_diff_a) + ($two_trait_diff_perc_b / $two_trait_diff_b)) / 2;
  }
  $two_trait_failed_might = 0;
  if ($two_trait_success != 'yes') {
    $two_trait_failed_might = round((($two_trait_diff_a + $two_trait_diff_b) / 2) * (1 - $two_trait_perc_diff));
  }

  // Combine results.
  return array(
    '<div>' . $two_trait_might_a . '</div><div style="border-top:1px solid;">' . $two_trait_might_b . '</div>', // Display the two.
    '<div>' . $two_trait_diff_a . '</div><div style="border-top:1px solid;">' . $two_trait_diff_b . '</div>', // Display the two.
    '<div>' . $two_trait_add_diff_a . '</div><div style="border-top:1px solid;">' . $two_trait_add_diff_b . '</div>', // Display the two.
    '<div>' . $two_trait_rolled_a . '</div><div style="border-top:1px solid;">' . $two_trait_rolled_b . '</div>', // Display the two.
    '<div>' . number_format($trait_a[4], 1) . '</div><div style="border-top:1px solid;">' . number_format($trait_b[4], 1) . '</div>', // Display the two.
    $two_trait_success,
    is_numeric($two_trait_winsby) ? number_format($two_trait_winsby) : $two_trait_winsby,
    is_numeric($two_trait_points) ? number_format($two_trait_points) : $two_trait_points,
    is_numeric($two_trait_perc_diff) ? number_format($two_trait_perc_diff, 2) : $two_trait_perc_diff,
    $two_trait_failed_might,
  );
}