<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once('cold_storage.features.inc');

/**
 * Implements hook_rules_action_info().
 */
function cold_storage_rules_action_info() {
  return array(
    'cold_storage_rules_unpub_nodes' => array(
      'label' => t('Unpublish user nodes'), 
      'parameter' => array(
        'user' => array(
          'type' => 'user',
          'label' => t('User'),
        ),
      ), 
      'group' => t('Cold storage'), 
    ),
    'cold_storage_rules_pub_nodes' => array(
      'label' => t('Publish user nodes'), 
      'parameter' => array(
        'user' => array(
          'type' => 'user',
          'label' => t('User'),
        ),
      ), 
      'group' => t('Cold storage'), 
    ),
  );
}

/**
 * Rules action handler.
 */
function cold_storage_rules_unpub_nodes($this_user) {
  $nodes = node_load_multiple(array(), array('uid' => $this_user->uid, 'type' => 'character-sheet'));
  foreach ($nodes as $node) {
    $node->status = 0;
    node_save($node);
  }
  // Flush Entity Cache record.
  if (module_exists('entitycache')) {
    cache_clear_all('*', 'cache_entity_node', TRUE);
  }
}

/**
 * Rules action handler.
 */
function cold_storage_rules_pub_nodes($this_user) {
  $nodes = node_load_multiple(array(), array('uid' => $this_user->uid, 'type' => 'character-sheet'));
  foreach ($nodes as $node) {
    $node->status = 1;
    node_save($node);
  }
  // Flush Entity Cache record.
  if (module_exists('entitycache')) {
    cache_clear_all('*', 'cache_entity_node', TRUE);
  }
}