<?php
/**
 * @file
 * Installation code for the Election.
 */

/**
 * Implements hook_schema().
 */
function department_schema() {}

/**
 * Implements hook_install().
 */
function department_install() {
  // Bump the weight down to make sure we can modify forms after proposal.
  db_query("UPDATE {system} SET weight = 20 WHERE name = 'department'");
}

/**
 * Implements hook_uninstall().
 */
function department_uninstall() {}
