<?php
/**
 * @file
 * Provide a search system into the old Vaxia archives.
 */

/**
 * Implements hook_permission().
 */
function item_helper_permission() {
  return array(
    'use item helper'=> array(
      'title' => t('use item helper'),
      'description' => t('Use item helper.'),
    ),
  );
}

/**
 * Form callback for the dice ruler form.
 * Mostly ajax driven results.
 */
function item_helper_form($form, &$form_state) {
  $form = array();
  $form['item_helper_style'] = array(
    '#type' => 'item',
    '#markup' => '<style>' .
      '#vaxia-dice-ruler-form .form-type-textfield{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#vaxia-dice-ruler-form #edit-a--3{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#vaxia-dice-ruler-form #edit-b--3{float:left;margin-left:1em;margin-top:0;margin-bottom:0;}' .
      '#vaxia-dice-ruler-form #item_helper_dice_results th{padding-left:0.5em;text-align:center;}'.
      '#vaxia-dice-ruler-form #item_helper_dice_results td{padding-left:0.5em;text-align:center;}'.
      '#vaxia-dice-ruler-form #item_helper_dice_help{float:right;clear:right;margin-top:1em;margin-left:1em;}'.
      '</style>',
  );

  // Select a type.
  $form['roll_type'] = array(
    '#type' => 'select',
    '#title' => t('Roll type'),
    '#options' => array(
      'hidden' => t('Hide roller'),
      'one_trait' => t('One trait'),
      'two_trait' => t('Two trait'),
      'trait_vs' => t('Trait vs. trait'),
      'combat' => t('Combat'),
      'magic' => t('Magic'),
    ),
    '#default_value' => 'hidden',
  );

  // Subforms for each type of roll. One trait.
  $form['one_trait'] = array(
    '#type' => 'fieldset',
    '#title' => t('One trait'),
    '#states' => array(
      'visible' => array(
        ':input[name="roll_type"]' => array('value' => 'one_trait'),
      ),
    ),
  );
  $form['one_trait']['one_trait_might'] = array(
    '#type' => 'textfield',
    '#title' => t('Might'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_diff'] = array(
    '#type' => 'textfield',
    '#title' => t('Diff.'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_add_diff'] = array(
    '#type' => 'textfield',
    '#title' => t('Add diff.'),
    '#size' => 5,
  );
  $form['one_trait']['one_trait_rolled'] = array(
    '#type' => 'textfield',
    '#title' => t('Rolled'),
    '#size' => 5,
  );

  // Provide button.
  $form['rule_dice'] = array(
    '#type' => 'button',
    '#value' => t('Rule roll'),
    '#ajax' => array(
      'callback' => 'item_helper_form_ajax',
      'wrapper' => 'item_helper_dice_results',
      'method' => 'replace',
      'effect' => 'fade',
    ),
    '#states' => array(
      'invisible' => array(
        ':input[name="roll_type"]' => array('value' => 'hidden'),
      ),
    ),
  );
  return $form;
}

/**
 * AJAX callback for ruling form.
 */
function item_helper_form_ajax($form, $form_state) {
  return $form['item_helper_dice_results'];
}